export const FORTUNES_DATA = [
  {
    "key": "Career",
    "icon": "💼",
    "vi": [
      "Thăng tiến vượt bậc, đạt đỉnh cao danh vọng, được công nhận toàn cầu. 👑✨",
      "Ký kết hợp đồng lớn, mở ra chương mới rực rỡ trong sự nghiệp. ✍️🚀",
      "Nhận được cơ hội mới đầy hứa hẹn, dự án thành công ngoài mong đợi. 💡📈",
      "Đồng nghiệp và cấp trên ủng hộ mạnh mẽ, công việc diễn ra suôn sẻ. 🤝👍",
      "Kỹ năng được cải thiện rõ rệt, mang lại hiệu quả công việc cao. 🎯⚙️",
      "Công việc ổn định, không có thay đổi lớn, cần kiên nhẫn chờ đợi thời cơ. 🗓️⏳",
      "Hoàn thành nhiệm vụ ở mức độ vừa phải, cần thêm nỗ lực để nổi bật. 📊➡️",
      "Có người hỗ trợ quý giá, giúp giải quyết khó khăn hiện tại. 🦸‍♂️💼",
      "Cân bằng tốt giữa công việc và cuộc sống cá nhân. ⚖️🧘",
      "Gặp trục trặc nhỏ với đồng nghiệp, dự án bị trì hoãn nhẹ. 🗣️🛑",
      "Cần học hỏi thêm kiến thức mới để bắt kịp xu hướng. 📚🌐",
      "Công việc lặp đi lặp lại, cảm thấy nhàm chán, cần tìm kiếm động lực. 🔄🥱",
      "Được giao trọng trách quan trọng, là bước đệm cho thăng tiến. 🥇🪜",
      "Cảnh báo về mất mát lớn, có thể mất việc hoặc thay đổi hướng đi hoàn toàn. 📉🚪",
      "Tiền lương không tăng, duy trì ở mức cũ. 💵🤷‍♀️",
      "Mọi kế hoạch công việc đều đi đúng hướng đã định. ✅🗺️",
      "Đối thủ cạnh tranh không quá mạnh, nhưng cũng cần đề phòng. 🛡️👀",
      "Có hiểu lầm nhỏ với cấp trên, cần giao tiếp rõ ràng hơn. 💬❌",
      "Đạt được vị trí lãnh đạo, dẫn dắt đội nhóm đi đến thành công. 🧑‍💼🏆",
      "Cần cải thiện khả năng quản lý thời gian để hiệu quả hơn. ⏱️⏫",
      "Khả năng giải quyết vấn đề xuất sắc, được mọi người tin tưởng. 🧠🔑",
      "Kết quả công việc phụ thuộc vào sự hợp tác của người khác. 🔗👥",
      "Có nguy cơ bị cắt giảm phúc lợi hoặc thưởng. ✂️💰",
      "Cần tìm kiếm sự đổi mới để tránh bị tụt hậu. ✨🔄",
      "Được đề cử giải thưởng hoặc danh hiệu danh giá trong ngành. 🏅🌟",
      "Sự nghiệp phát triển chậm nhưng chắc chắn. 🐢🧱",
      "Đối mặt với kiện tụng hoặc tranh chấp pháp lý liên quan đến công việc. ⚖️🚨",
      "Dự án hợp tác quốc tế mang lại danh tiếng. 🌍🌐",
      "Bị đối thủ chơi xấu hoặc lợi dụng lòng tin. 😈🤥",
      "Môi trường làm việc có nhiều thay đổi, cần thích nghi nhanh. 🌪️",
      "Tìm được niềm đam mê mới trong lĩnh vực mình đang làm. ❤️‍🔥🎯",
      "Cảm thấy kiệt sức, áp lực công việc quá lớn. 😥🔋",
      "Nên xem xét việc học thêm bằng cấp hoặc chứng chỉ. 🎓📝",
      "Công việc kinh doanh cá nhân có dấu hiệu khởi sắc. 🛍️💰",
      "Các mối quan hệ công việc đang được củng cố. 🔗🏗️",
      "Cẩn thận với các quyết định đầu tư mạo hiểm liên quan đến công ty. ⚠️🎲",
      "Giải quyết thành công một vấn đề nan giải đã tồn tại lâu nay. 🔓✔️",
      "Cần chú ý đến chi tiết và tính chính xác trong công việc. 🧐💯",
      "Được mời làm cố vấn hoặc chuyên gia hàng đầu. 🧑‍🏫🔝",
      "Có cơ hội chuyển đổi công việc sang lĩnh vực mới, cần cân nhắc. 🚪🤔",
      "Mất đi một đối tác/khách hàng quan trọng. 💔🤝",
      "Đã đến lúc xem xét lại mục tiêu sự nghiệp dài hạn của mình. 🧭🔮",
      "Có nguồn thu nhập thụ động mới từ công việc. 💸💻",
      "Bị kẻ xấu hãm hại, uy tín bị tổn thất nghiêm trọng. 🔪 reputation"
    ],
    "en": [
      "Rapid advancement, reaching the peak of fame, globally recognized. 👑✨",
      "Signing a major contract, opening a brilliant new chapter in your career. ✍️🚀",
      "Receiving a promising new opportunity, project succeeds beyond expectations. 💡📈",
      "Strong support from colleagues and superiors, work proceeds smoothly. 🤝👍",
      "Skills significantly improved, resulting in high work efficiency. 🎯⚙️",
      "Stable job with no major changes, patience is needed to wait for the right time. 🗓️⏳",
      "Completing tasks at a moderate level, more effort is needed to stand out. 📊➡️",
      "Valuable support from someone helps resolve current difficulties. 🦸‍♂️💼",
      "Good balance between work and personal life. ⚖️🧘",
      "Minor trouble with colleagues, project slightly delayed. 🗣️🛑",
      "Need to learn new knowledge to keep up with trends. 📚🌐",
      "Repetitive work feels boring, need to find motivation. 🔄🥱",
      "Entrusted with important responsibilities, a stepping stone for promotion. 🥇🪜",
      "Warning of major loss, possible job loss or a complete change in direction. 📉🚪",
      "Salary remains unchanged, maintaining the old level. 💵🤷‍♀️",
      "All work plans are going in the intended direction. ✅🗺️",
      "Competitors are not too strong, but caution is still needed. 🛡️👀",
      "Minor misunderstanding with superiors, clearer communication is needed. 💬❌",
      "Achieving a leadership position, leading the team to success. 🧑‍💼🏆",
      "Need to improve time management skills to be more effective. ⏱️⏫",
      "Excellent problem-solving skills, trusted by everyone. 🧠🔑",
      "Work results depend on the cooperation of others. 🔗👥",
      "Risk of benefits or bonus cuts. ✂️💰",
      "Seek innovation to avoid falling behind. ✨🔄",
      "Nominated for a prestigious industry award or title. 🏅🌟",
      "Career develops slowly but surely. 🐢🧱",
      "Facing litigation or legal disputes related to work. ⚖️🚨",
      "International cooperation project brings reputation. 🌍🌐",
      "Played foul by competitors or trust is exploited. 😈🤥",
      "Work environment has many changes, need to adapt quickly. 🌪️",
      "Finding new passion in your current field. ❤️‍🔥🎯",
      "Feeling exhausted, work pressure is too great. 😥🔋",
      "Should consider studying for more degrees or certificates. 🎓📝",
      "Personal business shows signs of flourishing. 🛍️💰",
      "Work relationships are being strengthened. 🔗🏗️",
      "Be careful with risky investment decisions related to the company. ⚠️🎲",
      "Successfully solving a difficult problem that has existed for a long time. 🔓✔️",
      "Need to pay attention to detail and accuracy in work. 🧐💯",
      "Invited to be a consultant or top expert. 🧑‍🏫🔝",
      "Opportunity to switch careers to a new field, need to consider. 🚪🤔",
      "Losing an important partner/client. 💔🤝",
      "Time to review your long-term career goals. 🧭🔮",
      "New passive income source from work. 💸💻",
      "Harmed by bad people, reputation seriously damaged. 🔪 reputation"
    ]
  },
  {
    "key": "Love",
    "icon": "❤️",
    "vi": [
      "Hôn nhân viên mãn, tình cảm thăng hoa, chuẩn bị cho một gia đình hạnh phúc. 💍👨‍👩‍👧‍👦",
      "Gặp được ý trung nhân, mối quan hệ tiến triển nhanh chóng và bền vững. 💘 tốc độ",
      "Mối quan hệ hiện tại ổn định, ít xung đột nhưng thiếu sự lãng mạn. 😌🧊",
      "Cãi vã nhỏ thường xuyên, cần học cách lắng nghe và thông cảm. 😠👂",
      "Tình yêu đôi lứa được gia đình, bạn bè ủng hộ. 👨‍👩‍👧‍👦 cheer",
      "Cần dành thêm thời gian và sự quan tâm cho đối phương. ⏰attention",
      "Độc thân sẽ sớm tìm thấy tình yêu đích thực tại một sự kiện bất ngờ. 🎯 surprise",
      "Mối quan hệ được nâng lên một tầm cao mới (Đính hôn/Kết hôn). 💎 level up",
      "Cảm thấy không chắc chắn về tương lai của mối quan hệ hiện tại. ❓🤔",
      "Cẩn thận với người thứ ba xen vào chuyện tình cảm. ⚠️👤",
      "Mối quan hệ lãng mạn quay trở lại, hoặc hàn gắn với người cũ. 🔙❤️‍🩹",
      "Tan vỡ hoặc chia tay đột ngột, gây ra sự đau khổ lớn. 💔😭",
      "Tình yêu đơn phương được đáp lại. 🏹 reciprocity",
      "Khoảng cách địa lý đang là thử thách cho mối quan hệ. ✈️ challenge",
      "Nghi ngờ và thiếu lòng tin đang làm rạn nứt tình cảm. 🧐 crack",
      "Có tin vui về con cái hoặc gia đình (nếu đã kết hôn). 👶 announcement",
      "Cần làm rõ ràng các ranh giới và kỳ vọng trong mối quan hệ. 🚧 expectation",
      "Mối quan hệ là nguồn động lực mạnh mẽ, giúp bạn phát triển bản thân. 💪 growth",
      "Những mâu thuẫn cũ chưa được giải quyết đang bùng phát trở lại. 💣 old issues",
      "Nên đi du lịch cùng nhau để hâm nóng tình cảm. 🏝️ warm up",
      "Sự thấu hiểu và sẻ chia đạt đến mức độ tuyệt vời. 🫂 understanding",
      "Tình trạng độc thân vẫn kéo dài, nhưng bạn đang học cách yêu thương bản thân. 🧍 self-love",
      "Bị lợi dụng tình cảm hoặc tài chính. 💸 exploit",
      "Bạn đang trở nên quá phụ thuộc vào đối phương. 🎣 dependent",
      "Bị lừa dối, sự thật phơi bày gây tổn thương sâu sắc. 🤥 deep hurt",
      "Tìm thấy sự cân bằng hoàn hảo giữa cá nhân và đối tác. ☯️ perfect",
      "Gặp gỡ nhiều người mới, nhưng chưa có ai thực sự phù hợp. 🚶‍♀️ search",
      "Một hành động lãng mạn bất ngờ từ đối phương. 🎁 surprise",
      "Cần giải quyết các vấn đề liên quan đến gia đình của đối phương. 🏡 resolve",
      "Cảm thấy cô đơn ngay cả khi đang trong mối quan hệ. 😔 alone",
      "Tình yêu bền chặt như kim cương, vượt qua mọi thử thách. 💎 strong",
      "Cần cải thiện khả năng thể hiện cảm xúc của mình. 🤐 express",
      "Mối quan hệ bạn bè thân thiết chuyển thành tình yêu lãng mạn. 👯‍♀️➡️❤️",
      "Sắp có một cuộc trò chuyện quan trọng định hình tương lai. 🗣️ shape",
      "Cần kiểm soát sự ghen tuông vô cớ. 😠 control",
      "Cần tập trung vào việc tự chữa lành trước khi tìm kiếm tình yêu mới. 🩹 focus",
      "Sự can thiệp từ bên ngoài phá hủy mối quan hệ. 🚧 break",
      "Cùng nhau vượt qua khó khăn tài chính hoặc sức khỏe. 🛡️ overcome",
      "Tình yêu đang ở giai đoạn \"trăng mật\" mới, hãy tận hưởng. 🍯 enjoy",
      "Tìm thấy tri kỷ không chỉ là người yêu. 🌟 soulmate",
      "Cảm thấy bị bỏ rơi hoặc không được ưu tiên. 👻 low priority",
      "Cần xem xét lại liệu bạn và đối phương có cùng mục tiêu sống hay không. 🎯 check",
      "Một lời xin lỗi chân thành hóa giải mọi mâu thuẫn. 🙏 resolve",
      "Được tận hưởng tình yêu vô điều kiện và sự hỗ trợ tuyệt đối. 🥰 support"
    ],
    "en": [
      "Fulfilling marriage, soaring emotions, preparing for a happy family. 💍👨‍👩‍👧‍👦",
      "Meeting your soulmate, the relationship progresses quickly and sustainably. 💘 speed",
      "Current relationship is stable, few conflicts but lacks romance. 😌🧊",
      "Frequent small arguments, need to learn to listen and sympathize. 😠👂",
      "Romance is supported by family and friends. 👨‍👩‍👧‍👦 cheer",
      "Need to dedicate more time and attention to your partner. ⏰attention",
      "Singles will soon find true love at an unexpected event. 🎯 surprise",
      "The relationship is taken to a new level (Engagement/Marriage). 💎 level up",
      "Feeling uncertain about the future of the current relationship. ❓🤔",
      "Be careful of a third party interfering in your love life. ⚠️👤",
      "Romantic relationship returns, or reconciling with an ex. 🔙❤️‍🩹",
      "Breakup or sudden separation causing great suffering. 💔😭",
      "Unrequited love is reciprocated. 🏹 reciprocity",
      "Geographical distance is a challenge for the relationship. ✈️ challenge",
      "Suspicion and lack of trust are cracking the feelings. 🧐 crack",
      "Good news about children or family (if married). 👶 announcement",
      "Need to clarify boundaries and expectations in the relationship. 🚧 expectation",
      "The relationship is a strong motivation, helping you grow. 💪 growth",
      "Old unresolved conflicts are flaring up again. 💣 old issues",
      "Should travel together to warm up feelings. 🏝️ warm up",
      "Understanding and sharing reach a wonderful level. 🫂 understanding",
      "Single status continues, but you are learning to love yourself. 🧍 self-love",
      "Being exploited emotionally or financially. 💸 exploit",
      "You are becoming too dependent on your partner. 🎣 dependent",
      "Being deceived, the truth revealed causes deep hurt. 🤥 deep hurt",
      "Finding the perfect balance between self and partner. ☯️ perfect",
      "Meeting many new people, but no one is truly suitable yet. 🚶‍♀️ search",
      "An unexpected romantic gesture from your partner. 🎁 surprise",
      "Need to resolve issues related to your partner's family. 🏡 resolve",
      "Feeling lonely even when in a relationship. 😔 alone",
      "Love as strong as a diamond, overcoming all challenges. 💎 strong",
      "Need to improve your ability to express emotions. 🤐 express",
      "Close friendship turns into romantic love. 👯‍♀️➡️❤️",
      "An important conversation shaping the future is coming. 🗣️ shape",
      "Need to control unreasonable jealousy. 😠 control",
      "Need to focus on self-healing before seeking new love. 🩹 focus",
      "External interference destroys the relationship. 🚧 break",
      "Overcoming financial or health difficulties together. 🛡️ overcome",
      "Love is in a new \"honeymoon\" phase, enjoy it. 🍯 enjoy",
      "Found a soulmate, not just a lover. 🌟 soulmate",
      "Feeling abandoned or not prioritized. 👻 low priority",
      "Need to review if you and your partner have the same life goals. 🎯 check",
      "A sincere apology resolves all conflicts. 🙏 resolve",
      "Enjoying unconditional love and absolute support. 🥰 support"
    ]
  },
  {
    "key": "Finance",
    "icon": "💰",
    "vi": [
      "Phát tài bất ngờ từ một nguồn thu không ngờ tới, tài sản tăng vọt. 💰🚀",
      "Đầu tư sinh lời lớn, đạt được tự do tài chính một phần. 📈 freedom",
      "Thu nhập ổn định, đủ trang trải chi tiêu và có chút dư dả. 💸 balance",
      "Gặp chi phí đột xuất lớn, cần phải rút tiền tiết kiệm. 🚨 drain",
      "Nhận được một khoản thừa kế hoặc quà tặng giá trị. 🎁 inherit",
      "Cần cắt giảm các chi tiêu không cần thiết. ✂️ reduce",
      "Một thương vụ kinh doanh mang lại lợi nhuận khổng lồ. 🤑 huge profit",
      "Các khoản nợ cũ được giải quyết hoàn toàn. 🔓 debt free",
      "Cần xem xét lại kế hoạch tiết kiệm và hưu trí. 🧐 retirement",
      "Bị lừa gạt trong một giao dịch nhỏ. 🤥 small scam",
      "Được tăng lương hoặc nhận thưởng xứng đáng. ⏫ raise",
      "Hao tài tốn của do quyết định đầu tư sai lầm nghiêm trọng. 📉 error",
      "Tìm thấy nguồn thu nhập thụ động mới và bền vững. 💻 new source",
      "Cần tham khảo ý kiến chuyên gia tài chính. 🧑‍💼 consult",
      "Tiền bạc bị thất lạc hoặc mất cắp. 👛 lost",
      "Mua được tài sản lớn (nhà, xe) với giá tốt. 🏠 new asset",
      "Tài chính chịu ảnh hưởng bởi tình hình kinh tế chung. 🌍 influence",
      "Sự giàu có đến từ trí tuệ và sự nỗ lực cá nhân. 🧠 effort",
      "Nợ nần chồng chất, cần có kế hoạch trả nợ khẩn cấp. 🆘 plan",
      "Có cơ hội hợp tác tài chính với người có kinh nghiệm. 🤝 mentor",
      "Cán cân thu chi hoàn toàn dương, dòng tiền ổn định. ➕ stable",
      "Cần cẩn thận khi cho người khác vay tiền. ⚠️ borrow",
      "Bị phạt tiền hoặc các khoản phí không đáng có. 🚨 fine",
      "Tiền bạc kiếm được từ công việc chân chính, không mạo hiểm. ⚖️ honest",
      "Phá sản hoặc mất trắng tài sản do rủi ro pháp lý. 💥 legal",
      "Có người giàu có hỗ trợ hoặc đầu tư vào ý tưởng của bạn. 🤑 invest",
      "Cần học cách đa dạng hóa nguồn thu nhập. 🌀 diversify",
      "May mắn về tiền bạc khi tham gia các trò chơi may rủi nhỏ. 🍀 small win",
      "Tài chính bị ảnh hưởng bởi vấn đề của người thân. 👨‍👩‍👧‍👦 relative",
      "Gặp khó khăn trong việc thu hồi các khoản nợ. 🚫 collect",
      "Sức mạnh tài chính cho phép bạn giúp đỡ người khác. 💖 help",
      "Cần theo dõi chặt chẽ các giao dịch tài khoản. 🔍 track",
      "Tiết kiệm được một khoản tiền lớn hơn mục tiêu đã định. 🎯 over target",
      "Chi tiêu cho sức khỏe và giáo dục tăng cao. 🏥 education",
      "Mất một cơ hội đầu tư tốt do do dự. ⌛ lost chance",
      "Mọi vấn đề tài chính sẽ được giải quyết trong vài tháng tới. ⏳ resolve",
      "Bị lôi kéo vào các mô hình tài chính lừa đảo. 🎣 fraud",
      "Bán được tài sản không sử dụng với giá cao. 💎 sell",
      "Cần xem xét việc mua bảo hiểm để bảo vệ tài sản. 🛡️ insurance",
      "Dòng tiền sẽ tăng mạnh trong quý tiếp theo. 🌊 cash flow",
      "Cẩn thận với các chi tiêu quá mức vào hàng hiệu. 🛍️ overspend",
      "Tiền bạc không phải là vấn đề lớn nhất hiện tại. 😌 not major",
      "Nhận được một khoản hoàn thuế lớn. 💵 refund",
      "Đạt được mọi mục tiêu tài chính đã đề ra trong năm nay. 🎯 achieved"
    ],
    "en": [
      "Unexpected wealth from an unforeseen source, assets skyrocket. 💰🚀",
      "High-yield investment, achieving partial financial freedom. 📈 freedom",
      "Stable income, enough to cover expenses with some surplus. 💸 balance",
      "Encountering large unexpected costs, need to withdraw savings. 🚨 drain",
      "Receiving a valuable inheritance or gift. 🎁 inherit",
      "Need to cut unnecessary expenses. ✂️ reduce",
      "A business deal brings huge profits. 🤑 huge profit",
      "Old debts are completely resolved. 🔓 debt free",
      "Need to review savings and retirement plans. 🧐 retirement",
      "Scammed in a small transaction. 🤥 small scam",
      "Getting a salary raise or a well-deserved bonus. ⏫ raise",
      "Loss of money due to a serious investment mistake. 📉 error",
      "Found a new and sustainable source of passive income. 💻 new source",
      "Need to consult a financial expert. 🧑‍💼 consult",
      "Money is lost or stolen. 👛 lost",
      "Purchased a large asset (house, car) at a good price. 🏠 new asset",
      "Finances affected by the general economic situation. 🌍 influence",
      "Wealth comes from intellect and personal effort. 🧠 effort",
      "Piling debts, need an urgent repayment plan. 🆘 plan",
      "Opportunity for financial cooperation with experienced people. 🤝 mentor",
      "Income and expenditure balance is positive, cash flow is stable. ➕ stable",
      "Be careful when lending money to others. ⚠️ borrow",
      "Fined or incurring unnecessary fees. 🚨 fine",
      "Money earned from honest work, not risk-taking. ⚖️ honest",
      "Bankruptcy or total loss of assets due to legal risks. 💥 legal",
      "A wealthy person supports or invests in your idea. 🤑 invest",
      "Need to learn how to diversify income sources. 🌀 diversify",
      "Financial luck when participating in small games of chance. 🍀 small win",
      "Finances affected by relatives' problems. 👨‍👩‍👧‍👦 relative",
      "Difficulty in collecting debts. 🚫 collect",
      "Financial strength allows you to help others. 💖 help",
      "Need to closely track account transactions. 🔍 track",
      "Saved a large amount exceeding the set target. 🎯 over target",
      "Expenses for health and education increase. 🏥 education",
      "Lost a good investment opportunity due to hesitation. ⌛ lost chance",
      "All financial problems will be resolved in the coming months. ⏳ resolve",
      "Lured into fraudulent financial models. 🎣 fraud",
      "Sold unused assets at a high price. 💎 sell",
      "Need to consider buying insurance to protect assets. 🛡️ insurance",
      "Cash flow will increase strongly in the next quarter. 🌊 cash flow",
      "Be careful with excessive spending on luxury goods. 🛍️ overspend",
      "Money is not the biggest problem right now. 😌 not major",
      "Receiving a large tax refund. 💵 refund",
      "Achieved all financial goals set for this year. 🎯 achieved"
    ]
  },
  {
    "key": "Health",
    "icon": "🩺",
    "vi": [
      "Khỏe mạnh sung mãn, tràn đầy năng lượng, miễn dịch vượt trội. 💪🔋",
      "Hồi phục nhanh chóng sau bệnh tật hoặc phẫu thuật. 🩹 fast recovery",
      "Sức khỏe ổn định, chỉ gặp bệnh vặt theo mùa. 🌡️ minor illness",
      "Gặp vấn đề tiêu hóa hoặc dị ứng nhẹ, cần thay đổi chế độ ăn. 🤢 change diet",
      "Tìm được phương pháp tập luyện/chữa trị phù hợp, hiệu quả. 🧘‍♀️ effective",
      "Cần cải thiện chất lượng giấc ngủ. 😴 improve",
      "Tinh thần minh mẫn, thể chất cường tráng, không có bệnh tật. 🧠 clean",
      "Kết quả kiểm tra sức khỏe tổng quát rất tốt. ✅ check",
      "Cần giảm căng thẳng và lo âu. 😟 relax",
      "Chấn thương nhỏ khi vận động hoặc làm việc nhà. 🤕 minor injury",
      "Cần tăng cường bổ sung vitamin và khoáng chất. 💊 supplement",
      "Bệnh nặng dai dẳng, cần điều trị lâu dài và tốn kém. 🏥 severe",
      "Cơ thể có khả năng tự chữa lành tốt. 🌿 self-heal",
      "Cần chú ý đến sức khỏe răng miệng và thị lực. 🦷👁️ attention",
      "Hệ thống miễn dịch suy yếu, dễ bị cảm lạnh. 🤧 weak",
      "Sức khỏe tinh thần được cải thiện rõ rệt. 💖 clear mind",
      "Cần kiểm soát cân nặng, tránh tăng hoặc giảm quá nhanh. ⚖️ weight",
      "Đạt được trạng thái cân bằng hoàn hảo về thể chất và tâm trí. ☯️ perfect balance",
      "Đau nhức xương khớp hoặc cơ bắp do tư thế làm việc sai. 🦴 incorrect posture",
      "Nên đi khám sức khỏe định kỳ sớm hơn dự kiến. 🩺 early check",
      "Bắt đầu một lối sống lành mạnh mới và duy trì tốt. 🌱 new routine",
      "Sức khỏe phụ thuộc vào môi trường sống và làm việc. 🏢 environment",
      "Mắc bệnh mãn tính nhẹ, cần thay đổi thói quen sinh hoạt. 😷 change habit",
      "Cần uống đủ nước và tránh các chất kích thích. 💧 avoid",
      "Tai nạn bất ngờ, cần phẫu thuật hoặc điều trị khẩn cấp. 💥 emergency",
      "Cảm thấy trẻ hơn nhiều so với tuổi thật. 👶 look younger",
      "Sức khỏe ổn định, không có gì đáng lo ngại. 😌 stable",
      "Tập thể dục mang lại niềm vui và sự sảng khoái. 🏃‍♀️ joy",
      "Cần giải quyết các vấn đề liên quan đến dị ứng theo mùa. 🤧 seasonal",
      "Mất ngủ kéo dài, ảnh hưởng đến năng suất làm việc. 😴 productivity",
      "Sức chịu đựng và khả năng phục hồi đáng kinh ngạc. 🛡️ amazing",
      "Cần tìm một hình thức thư giãn hiệu quả hơn. 🛀 effective relax",
      "Chế độ ăn uống cân bằng, mang lại nhiều lợi ích. 🍎 balanced diet",
      "Sức khỏe tâm linh đang được cải thiện. 🧘 spiritual",
      "Cẩn thận với các loại thuốc không rõ nguồn gốc. ⚠️ unknown medicine",
      "Cơ thể đang gửi tín hiệu cảnh báo nhẹ, cần chú ý. 🔔 slight warning",
      "Chẩn đoán sai lầm dẫn đến điều trị kém hiệu quả. ❌ wrong diagnosis",
      "Gia đình và người thân có sức khỏe tốt. 👨‍👩‍👧‍👦 family well",
      "Cần kiểm tra huyết áp và đường huyết thường xuyên. 🩸 check",
      "Quyết định thay đổi môi trường sống mang lại sức khỏe tốt hơn. 🏡 better health",
      "Cảm thấy mệt mỏi thường xuyên không rõ nguyên nhân. 😩 unexplained fatigue",
      "Sức khỏe phụ thuộc vào việc bạn có duy trì kỷ luật hay không. 📅 discipline",
      "Một loại thảo dược hoặc liệu pháp tự nhiên mang lại lợi ích lớn. 🌿 natural benefit",
      "Lối sống mới của bạn đang truyền cảm hứng cho người khác. ✨ inspire"
    ],
    "en": [
      "Vigorous health, full of energy, superior immunity. 💪🔋",
      "Rapid recovery after illness or surgery. 🩹 fast recovery",
      "Stable health, only minor seasonal illnesses. 🌡️ minor illness",
      "Digestive problems or mild allergies, need to change diet. 🤢 change diet",
      "Found a suitable and effective training/treatment method. 🧘‍♀️ effective",
      "Need to improve sleep quality. 😴 improve",
      "Mental clarity, strong physical body, no diseases. 🧠 clean",
      "General health check results are very good. ✅ check",
      "Need to reduce stress and anxiety. 😟 relax",
      "Minor injury during exercise or housework. 🤕 minor injury",
      "Need to increase vitamin and mineral intake. 💊 supplement",
      "Persistent severe illness, requiring long-term and expensive treatment. 🏥 severe",
      "The body has good self-healing capabilities. 🌿 self-heal",
      "Need to pay attention to dental health and vision. 🦷👁️ attention",
      "Weakened immune system, prone to colds. 🤧 weak",
      "Mental health significantly improved. 💖 clear mind",
      "Need to control weight, avoid gaining or losing too quickly. ⚖️ weight",
      "Achieving a state of perfect balance between body and mind. ☯️ perfect balance",
      "Joint pain or muscle aches due to incorrect working posture. 🦴 incorrect posture",
      "Should go for a periodic health check sooner than expected. 🩺 early check",
      "Starting a new healthy lifestyle and maintaining it well. 🌱 new routine",
      "Health depends on the living and working environment. 🏢 environment",
      "Mild chronic disease, need to change living habits. 😷 change habit",
      "Need to drink enough water and avoid stimulants. 💧 avoid",
      "Unexpected accident, requiring surgery or emergency treatment. 💥 emergency",
      "Feeling much younger than actual age. 👶 look younger",
      "Stable health, nothing to worry about. 😌 stable",
      "Exercise brings joy and refreshment. 🏃‍♀️ joy",
      "Need to resolve issues related to seasonal allergies. 🤧 seasonal",
      "Prolonged insomnia, affecting work productivity. 😴 productivity",
      "Amazing endurance and resilience. 🛡️ amazing",
      "Need to find a more effective form of relaxation. 🛀 effective relax",
      "Balanced diet brings many benefits. 🍎 balanced diet",
      "Spiritual health is improving. 🧘 spiritual",
      "Be careful with medicines of unknown origin. ⚠️ unknown medicine",
      "Body is sending slight warning signals, need to pay attention. 🔔 slight warning",
      "Misdiagnosis leads to ineffective treatment. ❌ wrong diagnosis",
      "Family and relatives are in good health. 👨‍👩‍👧‍👦 family well",
      "Need to check blood pressure and blood sugar frequently. 🩸 check",
      "Decision to change living environment brings better health. 🏡 better health",
      "Feeling tired frequently with no clear cause. 😩 unexplained fatigue",
      "Health depends on whether you maintain discipline or not. 📅 discipline",
      "A type of herb or natural therapy brings great benefits. 🌿 natural benefit",
      "Your new lifestyle is inspiring others. ✨ inspire"
    ]
  },
  {
    "key": "Overview",
    "icon": "🔮",
    "vi": [
      "Vạn sự như ý, mọi khía cạnh cuộc sống đều đạt đến sự hoàn hảo. 💯🌟",
      "May mắn bao bọc, mọi việc đều thuận lợi ngoài mong đợi. 🍀🎁",
      "Cuộc sống bình thường, không có biến động lớn, duy trì ổn định. 😌 steady",
      "Gặp nhiều trắc trở nhỏ liên tiếp, nhưng vẫn có thể kiểm soát. 🚧 minor block",
      "Đạt được mục tiêu quan trọng đã đặt ra từ lâu. 🎯 achieved",
      "Cần tập trung vào một lĩnh vực cụ thể để tạo đột phá. 💡 focus",
      "Nhận được sự bảo hộ mạnh mẽ từ vũ trụ hoặc quý nhân. 🛡️🦸‍♀️",
      "Mọi quyết định lớn trong thời gian này đều đúng đắn. ✅ big decision",
      "Cuộc sống đang ở giai đoạn \"chuyển mình\" chậm rãi. 🐌 transition",
      "Bị người khác hiểu lầm hoặc đánh giá sai. 🗣️ misunderstanding",
      "Cần học cách cân bằng giữa cho và nhận. ⚖️ give & take",
      "Đối mặt với khủng hoảng toàn diện về mọi mặt (sự nghiệp, tài chính, tình duyên). 💥 everything",
      "Cơ hội lớn đến từ một nơi xa xôi. ✈️ distant opportunity",
      "Cần sắp xếp lại các mối quan hệ xã hội. 👥 reorganize",
      "Cảm thấy thất vọng về một người thân cận. 😔 close person",
      "Cuộc sống cá nhân được cải thiện nhờ sự tự nhận thức. 🧘 self-aware",
      "Cần xem xét lại các giá trị cốt lõi của bản thân. 🧭 core values",
      "Cuộc sống là một chuỗi ngày hạnh phúc và thành công. 😊 continuous",
      "Bị ảnh hưởng bởi năng lượng tiêu cực từ môi trường xung quanh. ☁️ negative energy",
      "Mọi thứ đang diễn ra đúng như số phận đã định. 🌌 fate",
      "Sự sáng tạo và trực giác đang dẫn dắt bạn đi đúng hướng. 💡 follow gut",
      "Cần dành thời gian cho việc tự chăm sóc bản thân. 🛀 self-care",
      "Mất mát một vật phẩm có giá trị tinh thần. 💔 lost item",
      "Cần hoàn thành các công việc còn dang dở. 📝 complete",
      "Bị phản bội bởi người mà bạn tin tưởng nhất. 🔪 betrayal",
      "Tìm thấy mục đích sống rõ ràng hơn. 🧭 clear purpose",
      "Cuộc sống đòi hỏi sự kiên nhẫn và linh hoạt. 🧘 flexibility",
      "Gieo nhân tốt, gặt quả lành - những hành động tử tế được đền đáp. 🌼 karma",
      "Cần giải quyết các vấn đề còn tồn đọng trong quá khứ. 🕰️ past issues",
      "Cảm thấy cô lập và không được kết nối. 🧍 isolated",
      "Sống trọn vẹn từng khoảnh khắc, không hối tiếc. 💯 no regret",
      "Cần học cách buông bỏ những điều không thể kiểm soát. 🎈 let go",
      "Nhận được lời khen ngợi và sự tôn trọng từ cộng đồng. 👏 respect",
      "Sắp có một chuyến đi hoặc sự kiện lớn thay đổi tầm nhìn. 🌎 event",
      "Các mối quan hệ xã hội trở nên phức tạp và khó khăn. 🕸️ complicated",
      "Đã đến lúc thực hiện một thay đổi lớn trong đời sống cá nhân. 🔄 major change",
      "Vướng vào thị phi, danh tiếng bị hủy hoại. 🗣️ ruined name",
      "May mắn về mặt pháp lý hoặc các thủ tục hành chính. ⚖️ legal luck",
      "Cần giữ thái độ khiêm tốn và biết ơn. 🙏 humble",
      "Mọi thứ bạn chạm vào đều có khả năng thành công. 🍀 Midas touch",
      "Cần cẩn thận với những lời hứa hẹn quá lớn. ⚠️ over-promise",
      "Kết quả tổng thể phụ thuộc vào sự nỗ lực cá nhân. 💪 personal effort",
      "Có một người thầy/người cố vấn xuất hiện và giúp đỡ. 🧑‍🏫 mentor",
      "Đạt được giác ngộ tinh thần và sự bình yên nội tâm. 🕉️ inner peace"
    ],
    "en": [
      "Everything goes as wished, every aspect of life reaches perfection. 💯🌟",
      "Surrounded by luck, everything is favorable beyond expectations. 🍀🎁",
      "Normal life, no major fluctuations, maintaining stability. 😌 steady",
      "Encountering consecutive minor obstacles, but still controllable. 🚧 minor block",
      "Achieved important goals set long ago. 🎯 achieved",
      "Need to focus on a specific field to create a breakthrough. 💡 focus",
      "Received strong protection from the universe or a benefactor. 🛡️🦸‍♀️",
      "All major decisions during this time are correct. ✅ big decision",
      "Life is in a slow \"transition\" phase. 🐌 transition",
      "Misunderstood or misjudged by others. 🗣️ misunderstanding",
      "Need to learn how to balance giving and receiving. ⚖️ give & take",
      "Facing a comprehensive crisis in all aspects (career, finance, love). 💥 everything",
      "Great opportunity comes from a distant place. ✈️ distant opportunity",
      "Need to reorganize social relationships. 👥 reorganize",
      "Feeling disappointed about a close person. 😔 close person",
      "Personal life improved through self-awareness. 🧘 self-aware",
      "Need to review your core values. 🧭 core values",
      "Life is a series of happy and successful days. 😊 continuous",
      "Affected by negative energy from the surrounding environment. ☁️ negative energy",
      "Everything is happening exactly as fate intended. 🌌 fate",
      "Creativity and intuition are leading you in the right direction. 💡 follow gut",
      "Need to dedicate time to self-care. 🛀 self-care",
      "Loss of an item with sentimental value. 💔 lost item",
      "Need to complete unfinished tasks. 📝 complete",
      "Betrayed by the person you trust the most. 🔪 betrayal",
      "Found a clearer purpose in life. 🧭 clear purpose",
      "Life requires patience and flexibility. 🧘 flexibility",
      "Good deeds reap good rewards - kind actions are repaid. 🌼 karma",
      "Need to resolve issues lingering from the past. 🕰️ past issues",
      "Feeling isolated and unconnected. 🧍 isolated",
      "Living fully in every moment, no regrets. 💯 no regret",
      "Need to learn to let go of things you cannot control. 🎈 let go",
      "Received praise and respect from the community. 👏 respect",
      "A trip or major event is coming that changes your vision. 🌎 event",
      "Social relationships become complicated and difficult. 🕸️ complicated",
      "Time to make a major change in personal life. 🔄 major change",
      "Caught in scandal, reputation ruined. 🗣️ ruined name",
      "Luck in legal matters or administrative procedures. ⚖️ legal luck",
      "Need to keep a humble and grateful attitude. 🙏 humble",
      "Everything you touch has the potential for success. 🍀 Midas touch",
      "Be careful with promises that are too big. ⚠️ over-promise",
      "Overall result depends on personal effort. 💪 personal effort",
      "A teacher/mentor appears and helps. 🧑‍🏫 mentor",
      "Achieved spiritual enlightenment and inner peace. 🕉️ inner peace"
    ]
  },
  {
    "key": "Action advice",
    "icon": "🧭",
    "vi": [
      "Nên mạnh dạn tiến lên: Đây là thời điểm vàng để hành động và chấp nhận rủi ro. 🚀 DARE",
      "Hãy tin tưởng vào trực giác: Quyết định đầu tiên của bạn là đúng, hãy theo đuổi nó. 🧠 TRUST",
      "Cần suy nghĩ kỹ: Hãy lập kế hoạch chi tiết trước khi thực hiện bước tiếp theo. 📝 PLAN",
      "Tạm ngưng mọi việc mạo hiểm: Hạn chế các giao dịch lớn hoặc thay đổi đột ngột. 🛑 PAUSE",
      "Chủ động tìm kiếm sự giúp đỡ: Mọi người sẵn lòng hỗ trợ bạn. 🆘 ASK",
      "Cần đối mặt với sự thật: Đừng né tránh các vấn đề khó khăn. confronting",
      "Hành động ngay lập tức: Đừng để cơ hội tuột khỏi tay. 🏃‍♀️ NOW",
      "Giữ thái độ lạc quan: Niềm tin sẽ dẫn bạn đến thành công. 😊 POSITIVE",
      "Cần thay đổi cách tiếp cận: Phương pháp cũ không còn hiệu quả. 🔄 CHANGE",
      "Tránh xa những lời khuyên tiêu cực: Đừng để người khác làm bạn nhụt chí. 🚫 AVOID",
      "Nên tập trung vào những điều cơ bản: Đừng làm phức tạp hóa vấn đề. 🧱 BASIC",
      "Nên lùi lại hoàn toàn: Tạm hoãn tất cả các dự án lớn, thời điểm chưa thích hợp. 🔙 RETREAT",
      "Hãy là chính mình: Sự chân thật sẽ mang lại kết quả tốt. 🎭 BE YOU",
      "Cần kiên nhẫn hơn: Thành quả cần có thời gian để chín muồi. ⏳ PATIENCE",
      "Đừng tin tưởng bất cứ ai một cách mù quáng: Cần có sự đề phòng. ⚠️ DON'T TRUST",
      "Nên chia sẻ ý tưởng của bạn: Sự hợp tác sẽ mang lại lợi ích. 🗣️ SHARE",
      "Cần cân nhắc giữa lý trí và cảm xúc: Đừng để cảm xúc lấn át. 🧠❤️ BALANCE",
      "Mở rộng tầm nhìn: Đừng giới hạn bản thân trong khuôn khổ cũ. 🔭 EXPAND",
      "Tránh các tranh cãi không cần thiết: Hãy giữ sự im lặng. 🤫 SILENCE",
      "Cần sắp xếp lại ưu tiên: Liệt kê các việc cần làm theo thứ tự. 🔢 PRIORITY",
      "Đặt cược vào bản thân: Tự tin thể hiện khả năng. 🎯 BET",
      "Nên tha thứ và buông bỏ: Đừng để quá khứ cản trở hiện tại. 🙏 FORGIVE",
      "Không nên ký kết giấy tờ quan trọng: Cần xem xét lại điều khoản. 📄 REVIEW",
      "Cần dành thời gian nghỉ ngơi: Nạp lại năng lượng trước khi tiếp tục. 🔋 REST",
      "Thận trọng lời nói: Một lời nói vô ý có thể gây hậu quả nghiêm trọng. 🤐 CAREFUL",
      "Hành động theo kế hoạch đã định: Sự kỷ luật sẽ được đền đáp. 📅 FOLLOW",
      "Nên học hỏi từ những người đi trước: Tìm kiếm hình mẫu để noi theo. 🧑‍🏫 LEARN",
      "Thực hiện một hành động tử tế: Lòng tốt sẽ quay trở lại với bạn. 💖 KINDNESS",
      "Cần kết nối lại với thiên nhiên: Tìm lại sự bình yên trong tâm hồn. 🌳 CONNECT",
      "Tránh xa các địa điểm hoặc tình huống nguy hiểm: Cẩn tắc vô ưu. ⚠️ AVOID DANGER",
      "Định hình lại cuộc đời bạn: Đây là cơ hội để tái sinh. 🔄 REBIRTH",
      "Cần giữ bí mật các kế hoạch: Đừng tiết lộ quá sớm. 🤫 SECRETS",
      "Đầu tư vào giáo dục: Kiến thức là chìa khóa thành công. 📚 INVEST",
      "Nên tập trung vào chất lượng hơn số lượng: Làm ít nhưng làm tốt. 💎 QUALITY",
      "Không nên phản ứng thái quá: Hãy giữ bình tĩnh trong mọi tình huống. 😠 CALM",
      "Cần chấp nhận sự không hoàn hảo: Mọi thứ không cần phải tuyệt đối. 😌 ACCEPT",
      "Tuyệt đối không nên thay đổi công việc/người yêu: Quyết định sai lầm. ❌ NO CHANGE",
      "Bắt đầu một sở thích hoặc dự án mới: Khám phá tài năng tiềm ẩn. 🎨 START",
      "Nên hoàn thành các lời hứa: Giữ lời là giữ uy tín. ✅ KEEP PROMISE",
      "Hành động theo cảm hứng bất chợt: Đôi khi, sự ngẫu hứng mang lại điều tuyệt vời. ✨ INSPIRE",
      "Cẩn thận với các chi tiêu lớn: Tiền bạc có thể thất thoát. 💸 CAREFUL SPEND",
      "Cần xem xét ý kiến phản hồi: Lắng nghe lời chỉ trích mang tính xây dựng. 👂 FEEDBACK",
      "Tận dụng các mối quan hệ xã hội: Mạng lưới quan hệ là tài sản quý giá. 👥 NETWORK",
      "Bước ra khỏi vùng an toàn: Chỉ có thử thách mới tạo ra sự vĩ đại. 🏞️ STEP OUT"
    ],
    "en": [
      "Be bold and move forward: This is the golden time to act and take risks. 🚀 DARE",
      "Trust your intuition: Your first decision is right, pursue it. 🧠 TRUST",
      "Think carefully: Make a detailed plan before taking the next step. 📝 PLAN",
      "Pause all risky activities: Limit large transactions or sudden changes. 🛑 PAUSE",
      "Proactively seek help: Everyone is willing to support you. 🆘 ASK",
      "Face the truth: Do not avoid difficult problems. confronting",
      "Act immediately: Do not let the opportunity slip away. 🏃‍♀️ NOW",
      "Keep an optimistic attitude: Faith will lead you to success. 😊 POSITIVE",
      "Change your approach: The old method is no longer effective. 🔄 CHANGE",
      "Stay away from negative advice: Do not let others discourage you. 🚫 AVOID",
      "Focus on the basics: Do not overcomplicate the problem. 🧱 BASIC",
      "Retreat completely: Postpone all major projects, the time is not right. 🔙 RETREAT",
      "Be yourself: Authenticity will bring good results. 🎭 BE YOU",
      "Be more patient: Results need time to ripen. ⏳ PATIENCE",
      "Do not trust anyone blindly: Precaution is needed. ⚠️ DON'T TRUST",
      "Share your ideas: Cooperation will bring benefits. 🗣️ SHARE",
      "Balance reason and emotion: Do not let emotions take over. 🧠❤️ BALANCE",
      "Expand your vision: Do not limit yourself to old frameworks. 🔭 EXPAND",
      "Avoid unnecessary arguments: Keep your silence. 🤫 SILENCE",
      "Reorganize priorities: List things to do in order. 🔢 PRIORITY",
      "Bet on yourself: Confidently show your abilities. 🎯 BET",
      "Forgive and let go: Do not let the past hinder the present. 🙏 FORGIVE",
      "Do not sign important papers: Need to review terms. 📄 REVIEW",
      "Take time to rest: Recharge energy before continuing. 🔋 REST",
      "Be careful with words: A careless word can cause serious consequences. 🤐 CAREFUL",
      "Act according to the set plan: Discipline will be rewarded. 📅 FOLLOW",
      "Learn from predecessors: Find a role model to follow. 🧑‍🏫 LEARN",
      "Perform an act of kindness: Kindness will return to you. 💖 KINDNESS",
      "Reconnect with nature: Find peace in your soul. 🌳 CONNECT",
      "Stay away from dangerous places or situations: Better safe than sorry. ⚠️ AVOID DANGER",
      "Reshape your life: This is an opportunity for rebirth. 🔄 REBIRTH",
      "Keep plans secret: Do not reveal too soon. 🤫 SECRETS",
      "Invest in education: Knowledge is the key to success. 📚 INVEST",
      "Focus on quality over quantity: Do less but do it well. 💎 QUALITY",
      "Do not overreact: Keep calm in all situations. 😠 CALM",
      "Accept imperfection: Everything does not need to be absolute. 😌 ACCEPT",
      "Absolutely do not change jobs/partners: Wrong decision. ❌ NO CHANGE",
      "Start a new hobby or project: Discover hidden talents. 🎨 START",
      "Fulfill promises: Keeping your word is keeping your reputation. ✅ KEEP PROMISE",
      "Act on impulse: Sometimes, improvisation brings great things. ✨ INSPIRE",
      "Be careful with large expenses: Money can be lost. 💸 CAREFUL SPEND",
      "Consider feedback: Listen to constructive criticism. 👂 FEEDBACK",
      "Leverage social relationships: Networking is a valuable asset. 👥 NETWORK",
      "Step out of your comfort zone: Only challenges create greatness. 🏞️ STEP OUT"
    ]
  },
  {
    "key": "Future outlook",
    "icon": "⏳",
    "vi": [
      "Tầm nhìn rõ ràng: Tương lai xán lạn, mọi ước mơ đều trở thành hiện thực. 💎✨",
      "Mọi thứ diễn ra suôn sẻ: Không có trở ngại lớn nào xuất hiện. 🏞️ smooth",
      "Khó đoán: Tương lai phụ thuộc nhiều vào quyết định ở hiện tại. ❓ now",
      "Tương lai mờ mịt: Cần thay đổi chiến lược lớn để tránh rủi ro. 🌫️ change strategy",
      "Sẽ có một sự kiện lớn thay đổi tích cực cuộc đời bạn. 🎁 positive event",
      "Sự nghiệp ổn định, nhưng tình duyên có chút trục trặc. 💼❤️ minor issue",
      "Bạn sẽ được công nhận là người dẫn đầu trong lĩnh vực của mình. 🏆 leader",
      "Gia đình sẽ có thêm thành viên mới (con cái, cháu chắt...). 👶 new member",
      "Cần giải quyết một vấn đề cũ trước khi bước sang trang mới. 🕰️ resolve",
      "Sẽ có sự chia ly hoặc mất mát một người bạn thân. 💔 loss friend",
      "Cuộc sống sẽ ổn định lại sau 6 tháng nữa. ⏳ stable",
      "Một thảm họa nhỏ hoặc sự kiện không mong muốn sẽ xảy ra. 💥 disaster",
      "Sẽ đi du lịch đến nơi bạn luôn mơ ước. ✈️ dream travel",
      "Cần tập trung vào việc học một kỹ năng mới. 📚 new skill",
      "Sẽ có tranh chấp về tài sản hoặc tiền bạc. 💸 dispute",
      "Mối quan hệ với người thân sẽ được hàn gắn. 🫂 mend",
      "Sẽ có một thay đổi nhỏ trong công việc hàng ngày. 🔄 small change",
      "Bạn sẽ đạt đến sự tự do tài chính và tinh thần. 💰🧘 freedom",
      "Sẽ có người ghen tị và tìm cách hãm hại bạn. 😈 jealousy",
      "Sẽ có một cơ hội làm việc ở nước ngoài, cần cân nhắc. 🌎 abroad",
      "Sức khỏe sẽ được cải thiện đáng kể nhờ chế độ mới. 💪 improvement",
      "Mọi sự kiện lớn đều bị trì hoãn ngoài ý muốn. 🛑 delay",
      "Sẽ phải đối mặt với một quyết định khó khăn về đạo đức. ⚖️ moral dilemma",
      "Sẽ có một người lạ mặt mang đến tin tức quan trọng. 👤 news",
      "Một bí mật lớn sẽ được phơi bày, gây xáo trộn cuộc sống. 🤫 expose",
      "Sẽ tìm thấy một nguồn cảm hứng mới trong nghệ thuật. 🎨 inspiration",
      "Cuộc sống sẽ chuyển sang một nhịp điệu chậm và bình yên hơn. 🐢 peaceful",
      "Sự nghiệp sẽ thăng hoa nhờ một người cố vấn. 🧑‍🏫 career boost",
      "Sẽ có một cuộc đoàn tụ bất ngờ với người thân. 👨‍👩‍👧‍👦 reunion",
      "Cần cẩn thận với các vấn đề liên quan đến pháp luật. ⚠️ legal issue",
      "Bạn sẽ trở thành biểu tượng hoặc người truyền cảm hứng cho nhiều người. ✨ icon",
      "Tương lai gần là ổn định, nhưng tương lai xa cần chuẩn bị. 🧭 prepare",
      "Mối quan hệ yêu đương sẽ tiến tới cam kết nghiêm túc. 💍 commit",
      "Sẽ có một dự án cá nhân mang lại niềm vui lớn. 😊 personal project",
      "Các mối quan hệ xã hội sẽ bị cắt giảm đáng kể. ✂️ reduce network",
      "Một thay đổi lớn về nơi ở hoặc môi trường sống. 🏡 move",
      "Tương lai đen tối nếu bạn không thay đổi thói quen xấu hiện tại. 😈 dark future",
      "Sẽ nhận được một lời mời hợp tác độc quyền. 🤝 exclusive",
      "Cuộc sống đang đi theo vòng lặp, cần phá vỡ thói quen. 🔄 break habit",
      "Sẽ có một sự kiện giúp bạn thay đổi quan điểm sống hoàn toàn. 💡 perspective",
      "Sự nghiệp gặp phải một đối thủ cạnh tranh mạnh. ⚔️ strong rival",
      "Mọi dự đoán sẽ trở nên vô hiệu do một yếu tố bên ngoài. 🌍 external factor",
      "Bạn sẽ tìm thấy niềm tin vào một lý tưởng cao đẹp hơn. 🙏 higher ideal",
      "Cuộc đời đạt đến đỉnh cao của sự viên mãn và thành công. 🔝 full success"
    ],
    "en": [
      "Clear vision: A bright future, all dreams come true. 💎✨",
      "Everything goes smoothly: No major obstacles appear. 🏞️ smooth",
      "Unpredictable: The future depends much on decisions in the present. ❓ now",
      "Cloudy future: Need to change major strategy to avoid risks. 🌫️ change strategy",
      "There will be a major event that positively changes your life. 🎁 positive event",
      "Stable career, but love life has some minor hiccups. 💼❤️ minor issue",
      "You will be recognized as a leader in your field. 🏆 leader",
      "The family will have a new member (child, grandchild...). 👶 new member",
      "Need to solve an old problem before turning a new page. 🕰️ resolve",
      "There will be a separation or loss of a close friend. 💔 loss friend",
      "Life will stabilize after 6 months. ⏳ stable",
      "A small disaster or unwanted event will occur. 💥 disaster",
      "Will travel to the place you always dreamed of. ✈️ dream travel",
      "Need to focus on learning a new skill. 📚 new skill",
      "There will be a dispute over assets or money. 💸 dispute",
      "Relationship with relatives will be mended. 🫂 mend",
      "There will be a small change in daily work. 🔄 small change",
      "You will reach financial and mental freedom. 💰🧘 freedom",
      "There will be people who are jealous and try to harm you. 😈 jealousy",
      "There will be an opportunity to work abroad, need to consider. 🌎 abroad",
      "Health will improve significantly thanks to a new regimen. 💪 improvement",
      "All major events are delayed unintentionally. 🛑 delay",
      "Will have to face a difficult moral decision. ⚖️ moral dilemma",
      "A stranger will bring important news. 👤 news",
      "A big secret will be exposed, disrupting life. 🤫 expose",
      "Will find a new source of inspiration in art. 🎨 inspiration",
      "Life will shift to a slower and more peaceful rhythm. 🐢 peaceful",
      "Career will soar thanks to a mentor. 🧑‍🏫 career boost",
      "There will be an unexpected reunion with relatives. 👨‍👩‍👧‍👦 reunion",
      "Be careful with legal issues. ⚠️ legal issue",
      "You will become an icon or inspire many people. ✨ icon",
      "Near future is stable, but far future needs preparation. 🧭 prepare",
      "Romantic relationship will proceed to serious commitment. 💍 commit",
      "There will be a personal project bringing great joy. 😊 personal project",
      "Social relationships will be significantly reduced. ✂️ reduce network",
      "A major change in residence or living environment. 🏡 move",
      "Dark future if you do not change current bad habits. 😈 dark future",
      "Will receive an exclusive partnership invitation. 🤝 exclusive",
      "Life is going in a loop, need to break the habit. 🔄 break habit",
      "There will be an event helping you completely change your life perspective. 💡 perspective",
      "Career encounters a strong competitor. ⚔️ strong rival",
      "All predictions will become invalid due to an external factor. 🌍 external factor",
      "You will find faith in a higher ideal. 🙏 higher ideal",
      "Life reaches the peak of fulfillment and success. 🔝 full success"
    ]
  },
  {
    "key": "Lucky color",
    "icon": "🎨",
    "vi": [
      "Vàng Kim Lấp Lánh: Thu hút tiền tài, quyền lực, và danh vọng tột đỉnh. 🥇👑",
      "Xanh Lá Cây Hy Vọng: Tăng trưởng, sức khỏe dồi dào, và sự tươi mới trong tâm hồn. 🌿💚",
      "Xám Nhạt Trung Tính: Giúp ổn định tâm lý, nhưng thiếu sự đột phá. 🤍⚖️",
      "Màu Đen (Cần Tránh): Hấp thụ năng lượng tiêu cực, cần thay đổi màu sắc. ⚫️ ❌",
      "Màu Xanh Dương Sâu Thẳm: May mắn trong giao tiếp và học tập. 🗣️📘",
      "Màu Trắng Tinh Khiết: Mang lại sự thanh lọc, nhưng dễ bị ảnh hưởng bởi môi trường. ⚪️ ⚖️",
      "Màu Tím Hoàng Gia: Quyền lực, trí tuệ siêu việt, và vận may về mặt tinh thần. 🟣 🧠",
      "Màu Đỏ Ruby: Đam mê, năng lượng dồi dào, và sức hút mãnh liệt trong tình duyên. ❤️‍🔥 💋",
      "Màu Cam Đất: Ổn định các mối quan hệ gia đình và cá nhân. 🟠 👨‍👩‍👧‍👦",
      "Màu Nâu Đục: Gây cảm giác trì trệ, khó khăn trong việc đưa ra quyết định. 🟤 🛑",
      "Màu Bạc Ánh Kim: Mang lại sự linh hoạt và sáng tạo. 🩶 💡",
      "Màu Đen Sẫm Hoàn Toàn: Thu hút rắc rối lớn, sự đen đủi bao phủ. ⚫️ 💀",
      "Màu Hồng Phấn: May mắn trong tình yêu lãng mạn và sự hòa hợp. 🩷 💍",
      "Màu Vàng Chanh Nhạt: Khuyến khích sự lạc quan, nhưng thiếu tính thực tế. 🟡 🤷‍♀️",
      "Màu Xanh Neon Gắt: Gây ra sự chú ý không mong muốn và phiền phức. 🟢 🚨",
      "Màu Xanh Ngọc Bảo: Tài lộc bất ngờ và sự bình an. 🟢 💰",
      "Màu Be Ấm: Sự thoải mái và cảm giác an toàn. 🟨 😌",
      "Màu Cầu Vồng: May mắn vô biên, tổng hòa mọi điều tốt lành. 🌈 ♾️",
      "Màu Đỏ Tía: Gây ra sự tức giận và xung đột. 🔴 😠",
      "Màu Xanh Bầu Trời: Giúp đầu óc thư giãn và sáng suốt. 🔵 🧠",
      "Màu Đồng Cổ: Mang lại sự bền vững và kinh nghiệm quý báu. 🟫 ⏳",
      "Màu Xanh Bộ Đội: Sự kiên cường và khả năng vượt qua thử thách. 🫒 💪",
      "Màu Vàng Bẩn: Tiền bạc bị thất thoát do sự thiếu cẩn trọng. 💰 💩",
      "Màu Xám Tro: Cần một sự thay đổi để thoát khỏi sự đơn điệu. 🩶 🔄",
      "Màu Đỏ Máu: Cảnh báo về tai nạn hoặc sự kiện gây tổn thương lớn. 🩸 ⚠️",
      "Màu San Hô: Thúc đẩy các mối quan hệ xã hội và tình bạn. 🍑 🫂",
      "Màu Hoa Oải Hương: Mang lại sự nhẹ nhàng và giảm bớt căng thẳng. 💜 😌",
      "Màu Xanh Hải Quân: Sức mạnh nội tâm và sự kỷ luật. 🟦 🛡️",
      "Màu Đào Nhạt: Khuyến khích sự sáng tạo trong công việc. 🍑 💡",
      "Màu Xanh Xám Lạnh: Gây cảm giác cô lập và lạnh nhạt. 🥶 🧍",
      "Màu Lục Bảo: Sự giàu có vĩnh cửu và sự bảo vệ khỏi điều xấu. 🟢 🛡️",
      "Màu Xanh Rêu: Sự kết nối với thiên nhiên và sự chữa lành. 🌳 🩹",
      "Màu Xanh Thổ Nhĩ Kỳ: May mắn trong du lịch và khám phá. 🩱 ✈️",
      "Màu Kem: Đem lại sự ấm áp và ổn định tinh thần. 🍦 🏠",
      "Màu Đen Xám Lẫn Lộn: Sự hỗn loạn và thiếu định hướng. ⚫️ ❓",
      "Màu Đỏ Son: Đem lại năng lượng, nhưng cần kiểm soát sự nóng vội. 🔴 💥",
      "Màu Đen/Đỏ Pha Loãng: Vận xui song hành, nên tránh xa mọi quyết định lớn. 💀 ❌",
      "Màu Vàng Rơm: Niềm vui và sự thành công nhỏ nhưng liên tục. 💛 🎉",
      "Màu Xanh Lá Mạ: Khuyến khích sự phát triển cá nhân. 🟢 🚀",
      "Màu Đen Huyền Bí (Kết hợp với Kim Cương): Sự quyền lực bí ẩn. ⚫️ 💎",
      "Màu Tím Than: Gây ra sự cô đơn và khó khăn trong giao tiếp. 🟣 🧍",
      "Màu Đồng Thau: Sự cần cù và kết quả xứng đáng. 🥉 💪",
      "Màu Xanh Biển Nhạt: Sự thanh thản và khả năng nhìn nhận vấn đề rõ ràng. 💙 🌊",
      "Màu Đỏ Cam Tươi: Sức sống mãnh liệt, tài lộc dồi dào, và danh tiếng. 🟠 🔥"
    ],
    "en": [
      "Sparkling Gold: Attracts wealth, power, and peak fame. 🥇👑",
      "Hopeful Green: Growth, abundant health, and freshness in the soul. 🌿💚",
      "Neutral Light Gray: Helps stabilize psychology, but lacks breakthrough. 🤍⚖️",
      "Black (Avoid): Absorbs negative energy, need to change color. ⚫️ ❌",
      "Deep Ocean Blue: Luck in communication and study. 🗣️📘",
      "Pure White: Brings purification, but easily influenced by the environment. ⚪️ ⚖️",
      "Royal Purple: Power, superior intellect, and spiritual luck. 🟣 🧠",
      "Ruby Red: Passion, abundant energy, and intense attraction in love. ❤️‍🔥 💋",
      "Earthy Orange: Stabilizes family and personal relationships. 🟠 👨‍👩‍👧‍👦",
      "Murky Brown: Causes a feeling of stagnation, difficulty in making decisions. 🟤 🛑",
      "Metallic Silver: Brings flexibility and creativity. 🩶 💡",
      "Pitch Black: Attracts big trouble, bad luck covers. ⚫️ 💀",
      "Pastel Pink: Luck in romantic love and harmony. 🩷 💍",
      "Pale Lemon Yellow: Encourages optimism, but lacks practicality. 🟡 🤷‍♀️",
      "Harsh Neon Green: Causes unwanted attention and annoyance. 🟢 🚨",
      "Emerald Green: Unexpected wealth and peace. 🟢 💰",
      "Warm Beige: Comfort and feeling of safety. 🟨 😌",
      "Rainbow: Infinite luck, a synthesis of all good things. 🌈 ♾️",
      "Crimson Red: Causes anger and conflict. 🔴 😠",
      "Sky Blue: Helps relax the mind and be clear-headed. 🔵 🧠",
      "Antique Bronze: Brings sustainability and valuable experience. 🟫 ⏳",
      "Army Green: Resilience and ability to overcome challenges. 🫒 💪",
      "Dirty Yellow: Money lost due to lack of caution. 💰 💩",
      "Ash Gray: Need a change to escape monotony. 🩶 🔄",
      "Blood Red: Warning of accident or event causing great injury. 🩸 ⚠️",
      "Coral: Promotes social relationships and friendship. 🍑 🫂",
      "Lavender: Brings lightness and reduces stress. 💜 😌",
      "Navy Blue: Inner strength and discipline. 🟦 🛡️",
      "Pale Peach: Encourages creativity in work. 🍑 💡",
      "Cold Grey Blue: Causes a feeling of isolation and coldness. 🥶 🧍",
      "Emerald: Eternal wealth and protection from evil. 🟢 🛡️",
      "Moss Green: Connection with nature and healing. 🌳 🩹",
      "Turquoise: Luck in travel and exploration. 🩱 ✈️",
      "Cream: Brings warmth and mental stability. 🍦 🏠",
      "Mixed Grey Black: Chaos and lack of direction. ⚫️ ❓",
      "Vermilion: Brings energy, but need to control impatience. 🔴 💥",
      "Diluted Black/Red: Bad luck goes hand in hand, should avoid all major decisions. 💀 ❌",
      "Straw Yellow: Joy and small but continuous success. 💛 🎉",
      "Young Rice Green: Encourages personal development. 🟢 🚀",
      "Mysterious Black (Combined with Diamond): Mysterious power. ⚫️ 💎",
      "Dark Violet: Causes loneliness and difficulty in communication. 🟣 🧍",
      "Brass: Diligence and worthy results. 🥉 💪",
      "Light Sea Blue: Serenity and ability to see problems clearly. 💙 🌊",
      "Bright Orange Red: Intense vitality, abundant wealth, and fame. 🟠 🔥"
    ]
  },
  {
    "key": "Lucky number",
    "icon": "🔢",
    "vi": [
      "Số 8 (Phát Tài): Sự giàu có, thịnh vượng vô hạn, và sự cân bằng hoàn hảo. 8️⃣ 🤑",
      "Số 6 (Lộc Lá): May mắn trong tình duyên, gia đạo ấm êm và tài lộc đủ đầy. 6️⃣ 🍀",
      "Số 4 (Bình Thường/Ổn Định): Sự ổn định, nhưng thiếu sự đột phá và mạo hiểm. 4️⃣ ⚖️",
      "Số 7 (Cần Cẩn Thận): Sự cô độc, thử thách tinh thần và sự cô lập. 7️⃣ ⚠️",
      "Số 9 (Hoàn Thành): Sự kết thúc viên mãn, thành tựu lớn trong mọi lĩnh vực. 9️⃣ ✅",
      "Số 11 (Số Chủ Đạo): Sự trực giác mạnh mẽ, nhưng dễ bị áp lực tinh thần. 1️⃣1️⃣ 🧠",
      "Số 3 (Tam Tài): Sự sáng tạo, niềm vui và sự phát triển mạnh mẽ. 3️⃣ 💡",
      "Số 1 (Độc Lập/Dẫn Đầu): Khởi đầu thuận lợi, khả năng lãnh đạo cao. 1️⃣ 🚀",
      "Số 2 (Cân Bằng): Sự hòa hợp trong mối quan hệ, nhưng dễ bị động. 2️⃣ ☯️",
      "Số 13 (Thử Thách): Thay đổi lớn không mong muốn, cần chuẩn bị tinh thần. 1️⃣3️⃣ 😥",
      "Số 10 (Sự Khởi Đầu Mới): Kết thúc chu kỳ cũ, mở ra chương mới. 1️⃣0️⃣ 🔄",
      "Số 0 (Sự Hư Vô): Mất mát hoàn toàn, không có gì còn lại. 0️⃣ 💥",
      "Số 28 (Nhân Đôi Sự Giàu Có): Tài chính tăng trưởng gấp bội. 2️⃣8️⃣ 💸",
      "Số 14 (Sự Cân Bằng Năng Động): Cần linh hoạt để đạt được thành công. 1️⃣4️⃣ 🤸",
      "Số 5 (Sự Bất Ổn): Thay đổi liên tục, cần thận trọng trong các quyết định. 5️⃣ ⚠️",
      "Số 33 (Số Chủ Đạo - Lòng Từ Bi): Thành công đến từ việc giúp đỡ người khác. 3️⃣3️⃣ 💖",
      "Số 22 (Số Chủ Đạo - Xây Dựng): Tiềm năng lớn, nhưng cần nỗ lực rất nhiều. 2️⃣2️⃣ 💪",
      "Số 79 (Phước Lành Vĩnh Cửu): Mọi điều tốt lành đều được ban tặng. 7️⃣9️⃣ 🌟",
      "Số 44 (Sự Giới Hạn): Bị hạn chế về tài chính và cơ hội. 4️⃣4️⃣ 🚧",
      "Số 12 (Sự Học Hỏi): Cần học hỏi từ kinh nghiệm đau thương. 1️⃣2️⃣ 📚",
      "Số 16 (Khởi Đầu Vàng): Sự may mắn bất ngờ trong sự nghiệp. 1️⃣6️⃣ 🥇",
      "Số 17 (Tiền Tài Trí Tuệ): Thành công đến từ sự thông minh. 1️⃣7️⃣ 🧠",
      "Số 19 (Mặt Trái Của Tự Do): Cần cẩn thận với sự tự do quá trớn. 1️⃣9️⃣ 😈",
      "Số 20 (Sự Hồi Phục): Mọi thứ đang dần trở lại quỹ đạo. 2️⃣0️⃣ 🔄",
      "Số 26 (Cạm Bẫy Lớn): Cảnh báo về lừa đảo và sự sụp đổ. 2️⃣6️⃣ 🚨",
      "Số 27 (Trực Giác Vô Song): Thành công đến từ việc lắng nghe bản thân. 2️⃣7️⃣ 👂",
      "Số 29 (Sự Chậm Trễ): Các kế hoạch bị trì hoãn, cần kiên nhẫn. 2️⃣9️⃣ ⏳",
      "Số 31 (Sự Sáng Tạo Hoàn Hảo): Đạt được thành công nhờ ý tưởng độc đáo. 3️⃣1️⃣ 💡",
      "Số 34 (Sự Cân Nhắc): Cần suy nghĩ kỹ trước khi hành động. 3️⃣4️⃣ 🤔",
      "Số 35 (Sự Mất Mát Nhỏ): Tổn thất nhẹ về tài sản. 3️⃣5️⃣ 💸",
      "Số 99 (Thành Tựu Tuyệt Đối): Đỉnh cao của mọi thành công. 9️⃣9️⃣ 🔝",
      "Số 37 (May Mắn Lãng Mạn): Tình duyên có khởi sắc nhỏ. 3️⃣7️⃣ 💖",
      "Số 40 (Nền Tảng Vững Chắc): Mọi thứ xây dựng được sẽ bền vững. 4️⃣0️⃣ 🧱",
      "Số 41 (Sự Đánh Đổi): Thành công đòi hỏi sự hy sinh. 4️⃣1️⃣ 🗡️",
      "Số 45 (Bị Ràng Buộc): Cảm thấy bị giới hạn bởi các quy tắc. 4️⃣5️⃣ ⛓️",
      "Số 48 (Sự Lao Động Cần Cù): Kết quả đến từ sự chăm chỉ. 4️⃣8️⃣ 👷",
      "Số 88 (Thịnh Vượng Bị Đánh Mất): Mất đi cơ hội giàu có vĩnh viễn. 8️⃣8️⃣ 💔",
      "Số 52 (Hành Động Quyết Đoán): Thành công đến từ sự mạnh mẽ. 5️⃣2️⃣ 💥",
      "Số 55 (Sự Thay Đổi Cần Thiết): Đã đến lúc đổi mới hoàn toàn. 5️⃣5️⃣ 🔄",
      "Số 68 (Lộc Phát): May mắn liên tục về tài chính và sự nghiệp. 6️⃣8️⃣ 🍀",
      "Số 60 (Sự Chậm Chạp): Tiến độ công việc rất chậm, thiếu động lực. 6️⃣0️⃣ 🐢",
      "Số 71 (Sự Quan Sát): Cần xem xét tình hình kỹ lưỡng. 7️⃣1️⃣ 🔎",
      "Số 77 (May Mắn Tinh Thần): Sự bình yên và giác ngộ nội tâm. 7️⃣7️⃣ 🧘",
      "Số 168 (Nhất Lộc Phát): Sự may mắn, tài lộc liên tục trong suốt cuộc đời. 1️⃣6️⃣8️⃣ 💰"
    ],
    "en": [
      "Number 8 (Prosperity): Infinite wealth, prosperity, and perfect balance. 8️⃣ 🤑",
      "Number 6 (Fortune): Luck in love, peaceful family, and sufficient wealth. 6️⃣ 🍀",
      "Number 4 (Normal/Stable): Stability, but lacks breakthrough and risk-taking. 4️⃣ ⚖️",
      "Number 7 (Caution): Loneliness, spiritual challenge, and isolation. 7️⃣ ⚠️",
      "Number 9 (Completion): Fulfilling ending, great achievements in all fields. 9️⃣ ✅",
      "Number 11 (Master Number): Strong intuition, but prone to mental pressure. 1️⃣1️⃣ 🧠",
      "Number 3 (Creativity/Joy): Creativity, joy, and strong development. 3️⃣ 💡",
      "Number 1 (Independence/Leader): Favorable start, high leadership ability. 1️⃣ 🚀",
      "Number 2 (Balance): Harmony in relationships, but easily passive. 2️⃣ ☯️",
      "Number 13 (Challenge): Unwanted major change, need mental preparation. 1️⃣3️⃣ 😥",
      "Number 10 (New Beginning): Ending old cycle, opening new chapter. 1️⃣0️⃣ 🔄",
      "Number 0 (The Void): Complete loss, nothing remains. 0️⃣ 💥",
      "Number 28 (Double Wealth): Financial growth doubles. 2️⃣8️⃣ 💸",
      "Number 14 (Dynamic Balance): Need flexibility to achieve success. 1️⃣4️⃣ 🤸",
      "Number 5 (Instability): Continuous change, need caution in decisions. 5️⃣ ⚠️",
      "Number 33 (Master Number - Compassion): Success comes from helping others. 3️⃣3️⃣ 💖",
      "Number 22 (Master Number - Builder): Great potential, but requires a lot of effort. 2️⃣2️⃣ 💪",
      "Number 79 (Eternal Blessing): All good things are bestowed. 7️⃣9️⃣ 🌟",
      "Number 44 (Limitation): Restricted in finances and opportunities. 4️⃣4️⃣ 🚧",
      "Number 12 (Learning): Need to learn from painful experiences. 1️⃣2️⃣ 📚",
      "Number 16 (Golden Start): Unexpected luck in career. 1️⃣6️⃣ 🥇",
      "Number 17 (Intellectual Wealth): Success comes from intelligence. 1️⃣7️⃣ 🧠",
      "Number 19 (Dark Side of Freedom): Be careful with excessive freedom. 1️⃣9️⃣ 😈",
      "Number 20 (Recovery): Everything is gradually returning to track. 2️⃣0️⃣ 🔄",
      "Number 26 (Big Trap): Warning of fraud and collapse. 2️⃣6️⃣ 🚨",
      "Number 27 (Unrivaled Intuition): Success comes from listening to yourself. 2️⃣7️⃣ 👂",
      "Number 29 (Delay): Plans are delayed, patience is needed. 2️⃣9️⃣ ⏳",
      "Number 31 (Perfect Creativity): Achieve success thanks to unique ideas. 3️⃣1️⃣ 💡",
      "Number 34 (Consideration): Need to think carefully before acting. 3️⃣4️⃣ 🤔",
      "Number 35 (Small Loss): Slight loss of assets. 3️⃣5️⃣ 💸",
      "Number 99 (Absolute Achievement): The peak of all success. 9️⃣9️⃣ 🔝",
      "Number 37 (Romantic Luck): Love life has small improvements. 3️⃣7️⃣ 💖",
      "Number 40 (Solid Foundation): Everything built will be sustainable. 4️⃣0️⃣ 🧱",
      "Number 41 (Trade-off): Success demands sacrifice. 4️⃣1️⃣ 🗡️",
      "Number 45 (Bound): Feeling limited by rules. 4️⃣5️⃣ ⛓️",
      "Number 48 (Hard Labor): Results come from hard work. 4️⃣8️⃣ 👷",
      "Number 88 (Lost Prosperity): Losing the opportunity for wealth forever. 8️⃣8️⃣ 💔",
      "Number 52 (Decisive Action): Success comes from strength. 5️⃣2️⃣ 💥",
      "Number 55 (Necessary Change): Time for complete innovation. 5️⃣5️⃣ 🔄",
      "Number 68 (Fortune & Growth): Continuous luck in finance and career. 6️⃣8️⃣ 🍀",
      "Number 60 (Slowness): Work progress is very slow, lack of motivation. 6️⃣0️⃣ 🐢",
      "Number 71 (Observation): Need to review the situation carefully. 7️⃣1️⃣ 🔎",
      "Number 77 (Spiritual Luck): Inner peace and enlightenment. 7️⃣7️⃣ 🧘",
      "Number 168 (Prosperity for Life): Continuous luck and wealth throughout life. 1️⃣6️⃣8️⃣ 💰"
    ]
  },
  {
    "key": "Lucky food",
    "icon": "🍽️",
    "vi": [
      "Thịt Cá Đầy Đủ: Mang lại năng lượng dồi dào, sự sung túc và sức mạnh thể chất. 🥩🐟 💪",
      "Rau Xanh Tươi Tốt: Sức khỏe cải thiện, tinh thần sảng khoái, và sự thanh lọc. 🥬✨",
      "Ngũ Cốc Ổn Định: Duy trì sự cân bằng, nhưng thiếu sự đột phá về sức khỏe. 🍚 ⚖️",
      "Thức Ăn Nhanh Độc Hại: Cảnh báo về sức khỏe suy yếu và sự trì trệ. 🍔 🛑",
      "Trái Cây Nhiệt Đới: May mắn trong tình yêu và sự vui vẻ. 🥭 💖",
      "Các Món Ăn Truyền Thống: Sự ổn định trong gia đình và tinh thần. 🍜 👨‍👩‍👧‍👦",
      "Hải Sản Tươi Sống: Mang lại sự giàu có và khả năng sáng tạo. 🦞 💡",
      "Thực Phẩm Lên Men (Kim Chi/Dưa Muối): Tăng cường khả năng miễn dịch và sức mạnh nội tâm. 🌶️ 🛡️",
      "Món Ăn Cay: Kích thích tinh thần, nhưng dễ gây nóng vội. 🌶️ 🔥",
      "Đồ Uống Có Gas: Gây ra sự bồn chồn và các vấn đề về sức khỏe. 🥤 ⚠️",
      "Sữa và Các Sản Phẩm Từ Sữa: Sự ấm áp và hỗ trợ từ gia đình. 🥛 🏡",
      "Thức Ăn Quá Hạn: Cảnh báo về bệnh tật và sự xui xẻo lớn. 🦠 💀",
      "Mật Ong/Đường Mía: Cuộc sống ngọt ngào, may mắn trong các mối quan hệ. 🍯 🥰",
      "Nước Lọc Tinh Khiết: Cần thanh lọc cơ thể và tâm trí. 💧 🧘",
      "Thức Ăn Chiên Rán: Gây ra sự ì ạch, ảnh hưởng đến hiệu suất công việc. 🍟 🐢",
      "Nấm và Các Loại Thảo Dược: Khả năng chữa lành và sự thông thái. 🍄 🧠",
      "Cần Ăn Chậm và Cẩn Thận: Chú trọng đến quá trình hơn kết quả. 🐢 🧘",
      "Các Món Ăn Cung Đình: Vị thế xã hội được nâng cao. 👑 🍽️",
      "Rượu Mạnh Quá Mức: Gây ra sự mất kiểm soát và rắc rối. 🥃 ❌",
      "Thực Phẩm Ít Calo: Tốt cho sức khỏe, nhưng dễ thiếu năng lượng. 🥗 ⬇️",
      "Các Loại Đậu: Sự bền vững và tài chính ổn định. 🫘 💰",
      "Cần Ăn Cùng Người Thân: Tăng cường sự gắn kết gia đình. 👨‍👩‍👧‍👦 🤝",
      "Ăn Uống Vội Vàng: Bỏ lỡ cơ hội, gặp sự cố nhỏ. 💨 🤦‍♀️",
      "Cần Khám Phá Món Ăn Mới: Sự thay đổi nhỏ mang lại niềm vui. 🗺️ 😋",
      "Thức Ăn Tượng Trưng Cho Sự Đau Khổ: Cảm thấy chán nản và tiêu cực. 💔 😥",
      "Socola Đen: May mắn trong công việc sáng tạo và học tập. 🍫 🧠",
      "Các Món Ăn Chay Thanh Đạm: Tốt cho tâm linh, nhưng cần cân bằng dinh dưỡng. 🧘 ⚖️",
      "Hạt và Các Loại Quả Khô: Sự tích lũy tài sản và kinh nghiệm. 🌰 💰",
      "Cần Tự Nấu Ăn: Sự chủ động sẽ mang lại may mắn. 🍳 💡",
      "Ăn Uống Quá Độ: Gây ra sự nặng nề về thể chất và tinh thần. 🐷 😫",
      "Thực Phẩm Địa Phương Tươi Sạch: Sức khỏe tuyệt vời và sự kết nối. 🥬 🌎",
      "Cà Phê/Trà: Giúp tỉnh táo, nhưng dễ gây lo âu. ☕ 😟",
      "Bánh Mì Tươi: May mắn trong việc bắt đầu dự án mới. 🍞 🚀",
      "Cần Ăn Uống Theo Giờ Giấc: Sự kỷ luật mang lại kết quả tốt. ⏰ 📅",
      "Các Món Ăn Quá Mặn: Gây ra sự nóng nảy và xung đột. 🧂 😠",
      "Thực Phẩm Có Màu Vàng/Đỏ Tự Nhiên: Thu hút sự chú ý tích cực. 🟠 🤩",
      "Ăn Uống Một Mình Thường Xuyên: Cảm thấy cô đơn và không được hỗ trợ. 🧍 😭",
      "Bữa Ăn Thịnh Soạn: May mắn xã hội và tình bạn. 🥳 🤝",
      "Cần Ăn Ít Thịt Đỏ: Giảm bớt sự hung hăng. 🥩 ⬇️",
      "Bữa Ăn Cân Bằng Dinh Dưỡng: Sự hài hòa trong cuộc sống. ⚖️ ☯️",
      "Ăn Uống Trong Lúc Tức Giận: Tiêu hao năng lượng tích cực. 😠 📉",
      "Thực Phẩm Mùa Thu Hoạch: Kết quả đến từ sự chăm chỉ. 🌾 💪",
      "Nước Ép Trái Cây: Sự tươi mới và cơ hội mới. 🍹 💡",
      "Bữa Tiệc Sang Trọng Cùng Người Thương: Tình duyên và tài lộc viên mãn. 🥂 💖"
    ],
    "en": [
      "Full Meat & Fish: brings abundant energy, affluence, and physical strength. 🥩🐟 💪",
      "Fresh Green Vegetables: Improved health, refreshed spirit, and purification. 🥬✨",
      "Stable Grains/Cereals: Maintain balance, but lack health breakthroughs. 🍚 ⚖️",
      "Toxic Fast Food: Warning of weakened health and stagnation. 🍔 🛑",
      "Tropical Fruits: Luck in love and joy. 🥭 💖",
      "Traditional Dishes: Stability in family and spirit. 🍜 👨‍👩‍👧‍👦",
      "Fresh Seafood: Brings wealth and creativity. 🦞 💡",
      "Fermented Foods (Kimchi/Pickles): Boost immunity and inner strength. 🌶️ 🛡️",
      "Spicy Food: Stimulates the spirit, but easily causes impatience. 🌶️ 🔥",
      "Carbonated Drinks: Causes restlessness and health problems. 🥤 ⚠️",
      "Milk and Dairy Products: Warmth and support from family. 🥛 🏡",
      "Expired Food: Warning of illness and bad luck. 🦠 💀",
      "Honey/Sugar Cane: Sweet life, luck in relationships. 🍯 🥰",
      "Pure Water: Need to purify body and mind. 💧 🧘",
      "Fried Food: Causes sluggishness, affecting work performance. 🍟 🐢",
      "Mushrooms and Herbs: Healing ability and wisdom. 🍄 🧠",
      "Need to Eat Slowly and Carefully: Focus on the process rather than the result. 🐢 🧘",
      "Royal Dishes: Social status is elevated. 👑 🍽️",
      "Excessive Strong Alcohol: Causes loss of control and trouble. 🥃 ❌",
      "Low-Calorie Food: Good for health, but easily lack energy. 🥗 ⬇️",
      "Beans/Legumes: Sustainability and stable finances. 🫘 💰",
      "Need to Eat with Relatives: Strengthen family bonds. 👨‍👩‍👧‍👦 🤝",
      "Hasty Eating: Miss opportunities, encounter small incidents. 💨 🤦‍♀️",
      "Need to Explore New Dishes: Small changes bring joy. 🗺️ 😋",
      "Food Symbolizing Suffering: Feeling depressed and negative. 💔 😥",
      "Dark Chocolate: Luck in creative work and study. 🍫 🧠",
      "Light Vegetarian Dishes: Good for spirituality, but need balanced nutrition. 🧘 ⚖️",
      "Nuts and Dried Fruits: Accumulation of assets and experience. 🌰 💰",
      "Need to Cook Yourself: Proactivity will bring luck. 🍳 💡",
      "Overeating: Causes physical and mental heaviness. 🐷 😫",
      "Fresh Local Food: Excellent health and connection. 🥬 🌎",
      "Coffee/Tea: Helps stay alert, but easily causes anxiety. ☕ 😟",
      "Fresh Bread: Luck in starting new projects. 🍞 🚀",
      "Need to Eat on Time: Discipline brings good results. ⏰ 📅",
      "Overly Salty Dishes: Causes bad temper and conflict. 🧂 😠",
      "Natural Yellow/Red Foods: Attract positive attention. 🟠 🤩",
      "Eating Alone Frequently: Feeling lonely and unsupported. 🧍 😭",
      "Grand Feast: Social luck and friendship. 🥳 🤝",
      "Need to Eat Less Red Meat: Reduce aggression. 🥩 ⬇️",
      "Nutritionally Balanced Meal: Harmony in life. ⚖️ ☯️",
      "Eating While Angry: Drain positive energy. 😠 📉",
      "Harvest Season Food: Results come from hard work. 🌾 💪",
      "Fruit Juice: Freshness and new opportunities. 🍹 💡",
      "Luxury Party with Loved One: Fulfilling love and fortune. 🥂 💖"
    ]
  },
  {
    "key": "Success chance",
    "icon": "📈",
    "vi": [
      "90% Thành Công: Cơ hội lớn, chỉ cần một chút nỗ lực là đạt được. 9️⃣0️⃣ 🚀",
      "70% Thuận Lợi: Khá chắc chắn, nhưng vẫn cần đề phòng rủi ro nhỏ. 7️⃣0️⃣ ⚠️",
      "50/50: Kết quả phụ thuộc hoàn toàn vào quyết định và hành động hiện tại. 5️⃣0️⃣ ⚖️",
      "Dưới 20% Cần Nỗ Lực Gấp Đôi: Khả năng thất bại cao, cần thay đổi chiến lược. 2️⃣0️⃣ 😥",
      "85% Chắc Chắn: Sự ủng hộ từ bên ngoài giúp tăng tỷ lệ thành công. 8️⃣5️⃣ 🤝",
      "60% Khả Thi: Cần sự chuẩn bị kỹ lưỡng để vượt qua mức trung bình. 6️⃣0️⃣ 📝",
      "100% Khó Tin: Thành công ngoài sức tưởng tượng, phép màu xảy ra. 1️⃣0️⃣0️⃣ ✨",
      "75% Nhờ Vào Kinh Nghiệm: Các kỹ năng cũ sẽ giúp bạn chiến thắng. 7️⃣5️⃣ 🧠",
      "45% Thách Thức: Khả năng thành công thấp hơn thất bại một chút. 4️⃣5️⃣ 🧗",
      "15% Rủi Ro: Chỉ nên tiếp tục nếu bạn sẵn sàng chấp nhận mất mát. 1️⃣5️⃣ 💸",
      "55% Cần Quyết Đoán: Phải hành động dứt khoát thì mới thành công. 5️⃣5️⃣ 💥",
      "0% Vô Vọng: Không nên theo đuổi, dự án/mục tiêu này sẽ thất bại. 0️⃣ 💀",
      "80% Nhờ Vào Quan Hệ: Thành công đến từ sự giúp đỡ của quý nhân. 8️⃣0️⃣ 👥",
      "50% Do May Mắn: May mắn chiếm một nửa, cần nỗ lực phần còn lại. 5️⃣0️⃣ 🍀",
      "30% Cần Thay Đổi Lớn: Cần làm lại từ đầu để có hy vọng. 3️⃣0️⃣ 🔄",
      "95% Gần Như Tuyệt Đối: Mọi thứ đã được sắp đặt để bạn thành công. 9️⃣5️⃣ 🎯",
      "65% Chắc Chắn Với Kế Hoạch B: Kế hoạch chính không chắc chắn bằng kế hoạch dự phòng. 6️⃣5️⃣ 🛡️",
      "99.9% Tự Tin: Khả năng thành công là không thể nghi ngờ. 9️⃣9️⃣ 🥇",
      "25% Cần Cảnh Giác: Khả năng thất bại tiềm ẩn rất cao. 2️⃣5️⃣ 🚨",
      "40% Phụ Thuộc Vào Thời Điểm: Thành công nếu hành động đúng lúc. 4️⃣0️⃣ ⏰",
      "77% Nhờ Vào Sự Sáng Tạo: Thành công nhờ ý tưởng độc đáo. 7️⃣7️⃣ 💡",
      "50% Do Sự Cân Bằng: Phải cân bằng các yếu tố mới thành công. 5️⃣0️⃣ ☯️",
      "10% Rất Khó Khăn: Gần như không thể, cần sự can thiệp từ bên ngoài. 1️⃣0️⃣ 🆘",
      "62% Cần Thêm Tài Nguyên: Cần thêm tiền bạc hoặc người hỗ trợ. 6️⃣2️⃣ 💰",
      "Thành Công Bị Cản Trở: Sẽ thành công, nhưng bị hủy hoại ở phút cuối. 💀 🚧",
      "88% Thịnh Vượng: Thành công đi kèm với sự giàu có. 8️⃣8️⃣ 🤑",
      "58% Với Sự Kiên Nhẫn: Cần thời gian lâu hơn để đạt được. 5️⃣8️⃣ ⏳",
      "72% Nhờ Vào Sự Học Hỏi: Thành công đến từ việc thu thập kiến thức. 7️⃣2️⃣ 📚",
      "48% Cần Sự Lắng Nghe: Phải nghe lời khuyên mới có cơ hội. 4️⃣8️⃣ 👂",
      "18% Do Thiếu Chuẩn Bị: Thất bại do sự vội vàng. 1️⃣8️⃣ 🤦",
      "86% Với Lòng Tin Tuyệt Đối: Niềm tin là chìa khóa. 8️⃣6️⃣ 🙏",
      "51% Chỉ Hơn Một Nửa: Chỉ cần một chút may mắn là đủ. 5️⃣1️⃣ 🍀",
      "79% Nhờ Vào Kỷ Luật: Thành công đến từ sự chăm chỉ và bền bỉ. 7️⃣9️⃣ 📅",
      "42% Cần Sự Hợp Tác: Chỉ thành công khi có người đồng hành. 4️⃣2️⃣ 🤝",
      "28% Do Đối Thủ Mạnh: Cần vượt qua đối thủ rất mạnh. 2️⃣8️⃣ ⚔️",
      "53% Có Thể Đạt Được: Hãy tiếp tục nỗ lực. 5️⃣3️⃣ 💪",
      "Tỷ Lệ Thất Bại Cao Nhất: Không nên cố chấp, hãy rút lui. 0️⃣ 🛑",
      "69% Với Sự Đổi Mới: Thành công nếu dám thử cái mới. 6️⃣9️⃣ 🔄",
      "47% Do Thiếu Tập Trung: Cần tập trung hơn nữa. 4️⃣7️⃣ 🧠",
      "74% Nhờ Vào Lòng Dũng Cảm: Thành công đến từ việc dám đối diện. 7️⃣4️⃣ 🦁",
      "22% Cần Chi Phí Lớn: Khả năng thành công thấp, chi phí lại cao. 2️⃣2️⃣ 💸",
      "63% Với Nguồn Lực Đã Có: Đủ để thành công, nhưng cần tận dụng tối đa. 6️⃣3️⃣ ♻️",
      "82% Nhờ Vào Sự Tích Cực: Thái độ lạc quan mang lại chiến thắng. 8️⃣2️⃣ 😊",
      "93% Vượt Qua Mọi Giới Hạn: Khả năng thành công phi thường. 9️⃣3️⃣ 🚀"
    ],
    "en": [
      "90% Success: Huge opportunity, just a little effort needed to achieve it. 9️⃣0️⃣ 🚀",
      "70% Favorable: Quite certain, but still need to guard against small risks. 7️⃣0️⃣ ⚠️",
      "50/50: Result depends entirely on current decisions and actions. 5️⃣0️⃣ ⚖️",
      "Below 20% Double Effort Needed: High failure probability, need to change strategy. 2️⃣0️⃣ 😥",
      "85% Certain: Support from outside helps increase success rate. 8️⃣5️⃣ 🤝",
      "60% Feasible: Need thorough preparation to surpass average level. 6️⃣0️⃣ 📝",
      "100% Unbelievable: Success beyond imagination, miracle happens. 1️⃣0️⃣0️⃣ ✨",
      "75% Thanks to Experience: Old skills will help you win. 7️⃣5️⃣ 🧠",
      "45% Challenge: Success probability is slightly lower than failure. 4️⃣5️⃣ 🧗",
      "15% Risky: Should only continue if you are ready to accept loss. 1️⃣5️⃣ 💸",
      "55% Be Decisive: Must act decisively to succeed. 5️⃣5️⃣ 💥",
      "0% Hopeless: Should not pursue, this project/goal will fail. 0️⃣ 💀",
      "80% Thanks to Relations: Success comes from the help of benefactors. 8️⃣0️⃣ 👥",
      "50% Due to Luck: Luck takes half, need effort for the rest. 5️⃣0️⃣ 🍀",
      "30% Need Major Change: Need to start over to have hope. 3️⃣0️⃣ 🔄",
      "95% Almost Absolute: Everything is set for you to succeed. 9️⃣5️⃣ 🎯",
      "65% Certain with Plan B: Main plan is not as certain as backup plan. 6️⃣5️⃣ 🛡️",
      "99.9% Confident: Success probability is unquestionable. 9️⃣9️⃣ 🥇",
      "25% Be Vigilant: Potential failure probability is very high. 2️⃣5️⃣ 🚨",
      "40% Depends on Timing: Success if acted at the right time. 4️⃣0️⃣ ⏰",
      "77% Thanks to Creativity: Success thanks to unique ideas. 7️⃣7️⃣ 💡",
      "50% Due to Balance: Must balance factors to succeed. 5️⃣0️⃣ ☯️",
      "10% Very Difficult: Almost impossible, need intervention from outside. 1️⃣0️⃣ 🆘",
      "62% Need More Resources: Need more money or supporters. 6️⃣2️⃣ 💰",
      "Success Hindered: Will succeed, but ruined at the last minute. 💀 🚧",
      "88% Prosperous: Success comes with wealth. 8️⃣8️⃣ 🤑",
      "58% With Patience: Need longer time to achieve. 5️⃣8️⃣ ⏳",
      "72% Thanks to Learning: Success comes from gathering knowledge. 7️⃣2️⃣ 📚",
      "48% Need Listening: Must listen to advice to have a chance. 4️⃣8️⃣ 👂",
      "18% Due to Lack of Preparation: Failure due to haste. 1️⃣8️⃣ 🤦",
      "86% With Absolute Faith: Faith is the key. 8️⃣6️⃣ 🙏",
      "51% Just Over Half: Just a little luck is enough. 5️⃣1️⃣ 🍀",
      "79% Thanks to Discipline: Success comes from hard work and persistence. 7️⃣9️⃣ 📅",
      "42% Need Cooperation: Only succeed when having companions. 4️⃣2️⃣ 🤝",
      "28% Due to Strong Competitor: Need to overcome very strong opponent. 2️⃣8️⃣ ⚔️",
      "53% Achievable: Keep striving. 5️⃣3️⃣ 💪",
      "Highest Failure Rate: Do not be stubborn, retreat. 0️⃣ 🛑",
      "69% With Innovation: Success if daring to try new things. 6️⃣9️⃣ 🔄",
      "47% Due to Lack of Focus: Need to focus more. 4️⃣7️⃣ 🧠",
      "74% Thanks to Courage: Success comes from daring to face. 7️⃣4️⃣ 🦁",
      "22% High Cost Needed: Low success probability, high cost. 2️⃣2️⃣ 💸",
      "63% With Existing Resources: Enough to succeed, but need to maximize use. 6️⃣3️⃣ ♻️",
      "82% Thanks to Positivity: Optimistic attitude brings victory. 8️⃣2️⃣ 😊",
      "93% Beyond All Limits: Extraordinary success probability. 9️⃣3️⃣ 🚀"
    ]
  },
  {
    "key": "Journey & Travel",
    "icon": "🧳",
    "vi": [
      "Du lịch Tuyệt Vời: Một chuyến đi hoàn hảo, khám phá được nhiều điều ý nghĩa. 🏝️✨",
      "Chuyến Đi Suôn Sẻ: Mọi kế hoạch đều đúng lịch trình, không có rắc rối. ✅ 🗺️",
      "Cần Cẩn Thận: Cần chú ý đến hành lý và giấy tờ cá nhân. ⚠️ 📄",
      "Có Sự Cố Bất Ngờ: Trì hoãn chuyến bay hoặc mất một vật quan trọng. ✈️ 🚨",
      "Gặp Gỡ Bạn Đồng Hành Thú Vị: Mở rộng các mối quan hệ xã hội. 👥 🤝",
      "Cần Chuẩn Bị Thêm Tiền: Chi phí phát sinh cao hơn dự kiến. 💸 📈",
      "Hành Trình Chữa Lành: Chuyến đi mang lại sự bình yên và phục hồi tinh thần. 🧘 🩹",
      "May Mắn Về Chỗ Ở: Tìm được nơi lưu trú tuyệt vời ngoài mong đợi. 🏠 🏨",
      "Cần Linh Hoạt Thay Đổi Lịch Trình: Thời tiết hoặc điều kiện khác thay đổi. 🌦️ 🔄",
      "Lạc Đường Hoặc Mất Phương Hướng: Gây ra sự lo lắng và mất thời gian. 🧭 😥",
      "Du Lịch Tự Túc Mang Lại Nhiều Kinh Nghiệm: Phải tự mình giải quyết vấn đề. 🎒 💪",
      "Bị Hủy Chuyến Hoặc Tai Nạn: Một sự kiện nghiêm trọng cần phải hủy bỏ. ❌ 💥",
      "Khám Phá Một Địa Điểm Bí Ẩn: Mang lại niềm vui và kiến thức mới. 🗺️ 💡",
      "Cần Đi Du Lịch Ngắn Ngày: Không nên đi quá xa hoặc quá lâu. 📅 🤏",
      "Bị Móc Túi Hoặc Mất Ví Tiền: Cần hết sức cảnh giác. 🚨 👛",
      "Một Chuyến Công Tác Thành Công: Ký kết được hợp đồng lớn. 🤝 💼",
      "Cần Đi Cùng Người Lớn Tuổi: Họ sẽ mang lại sự bình an. 👵 🛡️",
      "Chuyến Đi Định Mệnh: Gặp gỡ người quan trọng thay đổi cuộc đời. 💘 ✨",
      "Gặp Khó Khăn Với Hải Quan/Thủ Tục: Các giấy tờ bị sai sót. 🛂 😥",
      "Du Lịch Một Mình Để Tự Chiêm Nghiệm: Cần thời gian riêng tư. 🧍 🧘",
      "Nhận Được Ưu Đãi Lớn: Tiết kiệm được chi phí đáng kể. 🎁 💰",
      "Cần Quay Trở Lại Nơi Chốn Cũ: Tìm lại ký ức hoặc giải quyết việc cũ. 🔙 🏡",
      "Ốm Đau Nhẹ Khi Đi Xa: Sức khỏe bị ảnh hưởng do thay đổi thời tiết. 🤧 🌡️",
      "Cần Chuẩn Bị Kế Hoạch Dự Phòng: Đề phòng mọi tình huống xấu. 📝 🛡️",
      "Rơi Vào Tình Huống Nguy Hiểm: Cảnh báo về an toàn tính mạng. ⚠️ 💀",
      "Du Lịch Để Kỷ Niệm: Kỷ niệm một sự kiện quan trọng. 📸 🎉",
      "Cần Đi Đến Vùng Biển: Biển sẽ mang lại sự tĩnh tâm. 🌊 😌",
      "Tìm Được Nơi Tuyệt Đẹp Để An Cư: Có cơ hội chuyển đến nơi mới. 🏡 💖",
      "Cần Đặt Trước Mọi Thứ: Sự chuẩn bị là chìa khóa. 🗝️ 📝",
      "Người Bạn Đồng Hành Gây Rắc Rối: Xung đột nhỏ trong chuyến đi. 🗣️ 😡",
      "Hành Trình Khai Sáng: Đạt được sự giác ngộ về tinh thần. 💡 🕉️",
      "Cần Mang Theo Vật May Mắn: Giúp xua đuổi điều xui xẻo. 🍀 🛡️",
      "Chuyến Đi Với Gia Đình Hòa Thuận: Tăng cường tình cảm. 👨‍👩‍👧‍👦 🥰",
      "Nên Đi Đến Vùng Núi: Giúp tăng cường sức mạnh ý chí. ⛰️ 💪",
      "Chi Tiêu Vượt Quá Ngân Sách: Tiền bạc bị thất thoát. 💸 📉",
      "Cần Học Ngôn Ngữ Địa Phương: Giúp chuyến đi thú vị hơn. 🗣️ 🌍",
      "Bị Cấm Xuất Cảnh/Nhập Cảnh: Gặp vấn đề pháp lý. 🚫 ⚖️",
      "Du Lịch Về Quê Hương: Tìm lại nguồn cội và sự bình yên. 🏡 😌",
      "Cần Kiểm Tra Lại Phương Tiện Di Chuyển: Đề phòng sự cố kỹ thuật. ⚙️ ⚠️",
      "Chuyến Đi Mang Lại Cảm Hứng Nghệ Thuật: Sự sáng tạo bùng nổ. 🎨 💡",
      "Bị Lỡ Hẹn Quan Trọng: Do sự chậm trễ của phương tiện. ⏰ ❌",
      "Cần Đi Đến Nơi Có Lịch Sử: Học hỏi từ quá khứ. 🏛️ 📚",
      "Được Ai Đó Bao Chi Phí: May mắn về tài chính du lịch. 🎁 ✈️",
      "Chuyến Đi Tuyệt Đỉnh Nhất Cuộc Đời: Kỷ niệm khó quên. 💯 🎉"
    ],
    "en": [
      "Wonderful Travel: A perfect trip, discovering many meaningful things. 🏝️✨",
      "Smooth Trip: All plans are on schedule, no trouble. ✅ 🗺️",
      "Be Careful: Need to pay attention to luggage and personal papers. ⚠️ 📄",
      "Unexpected Incident: Flight delay or losing an important item. ✈️ 🚨",
      "Meeting Interesting Companions: Expand social relationships. 👥 🤝",
      "Need to Prepare More Money: Costs incurred are higher than expected. 💸 📈",
      "Healing Journey: The trip brings peace and mental recovery. 🧘 🩹",
      "Luck with Accommodation: Found a wonderful place to stay beyond expectation. 🏠 🏨",
      "Need Flexibility in Schedule: Weather or other conditions change. 🌦️ 🔄",
      "Getting Lost or Disoriented: Causes anxiety and waste of time. 🧭 😥",
      "Self-Travel Brings Experience: Must solve problems yourself. 🎒 💪",
      "Trip Cancelled or Accident: A serious event requires cancellation. ❌ 💥",
      "Discovering a Mysterious Place: Brings joy and new knowledge. 🗺️ 💡",
      "Need Short Trip: Should not go too far or too long. 📅 🤏",
      "Pickpocketed or Lost Wallet: Need to be extremely vigilant. 🚨 👛",
      "Successful Business Trip: Signed a large contract. 🤝 💼",
      "Need to Go with Elders: They will bring peace. 👵 🛡️",
      "Destined Trip: Meeting an important person changing your life. 💘 ✨",
      "Difficulty with Customs/Procedures: Documents have errors. 🛂 😥",
      "Solo Travel for Self-Reflection: Need private time. 🧍 🧘",
      "Received Great Discount: Saved significant costs. 🎁 💰",
      "Need to Return to Old Place: Find memories or resolve old business. 🔙 🏡",
      "Mild Illness When Traveling: Health affected by weather change. 🤧 🌡️",
      "Need Backup Plan: Guard against all bad situations. 📝 🛡️",
      "Falling into Dangerous Situation: Warning about life safety. ⚠️ 💀",
      "Anniversary Travel: Celebrating an important event. 📸 🎉",
      "Need to Go to the Sea: The sea will bring peace of mind. 🌊 😌",
      "Found Beautiful Place to Settle: Opportunity to move to a new place. 🏡 💖",
      "Need to Book Everything in Advance: Preparation is key. 🗝️ 📝",
      "Companion Causes Trouble: Small conflict during the trip. 🗣️ 😡",
      "Enlightenment Journey: Achieved spiritual enlightenment. 💡 🕉️",
      "Need to Bring Lucky Charm: Helps ward off bad luck. 🍀 🛡️",
      "Trip with Harmonious Family: Strengthen affection. 👨‍👩‍👧‍👦 🥰",
      "Should Go to Mountains: Helps strengthen willpower. ⛰️ 💪",
      "Spending Over Budget: Money is lost. 💸 📉",
      "Need to Learn Local Language: Helps the trip be more interesting. 🗣️ 🌍",
      "Banned from Exit/Entry: Encounter legal problems. 🚫 ⚖️",
      "Trip to Hometown: Find roots and peace. 🏡 😌",
      "Need to Check Vehicle Again: Guard against technical issues. ⚙️ ⚠️",
      "Trip Brings Artistic Inspiration: Creativity explodes. 🎨 💡",
      "Missed Important Appointment: Due to vehicle delay. ⏰ ❌",
      "Need to Go to Historic Place: Learn from the past. 🏛️ 📚",
      "Expenses Covered by Someone: Financial luck in travel. 🎁 ✈️",
      "Best Trip of Life: Unforgettable memory. 💯 🎉"
    ]
  },
  {
    "key": "Mood",
    "icon": "😊",
    "vi": [
      "Hạnh Phúc Tột Độ: Tràn ngập niềm vui và sự thỏa mãn trong cuộc sống. 😄✨",
      "Vui Vẻ Thoải Mái: Tinh thần lạc quan, không có gánh nặng. 😊 🎈",
      "Bình Tĩnh và Ổn Định: Không có cảm xúc quá mạnh mẽ, giữ sự trung lập. 😌 ⚖️",
      "Buồn Rầu U Uất: Cảm thấy chán nản, cần tìm người chia sẻ. 😔 🌧️",
      "Hào Hứng và Đầy Đam Mê: Sẵn sàng cho những thử thách mới. 🔥 🚀",
      "Cảm Thấy Cô Đơn Nhẹ: Cần kết nối lại với bạn bè. 🧍 📞",
      "Tâm Hồn Thanh Thản: Đạt đến sự bình yên nội tâm hoàn toàn. 🧘 🕉️",
      "Biết Ơn và Hài Lòng: Cảm thấy may mắn với những gì đang có. 🙏 😊",
      "Cần Suy Nghĩ Kỹ: Tâm trạng dễ bị dao động bởi ý kiến người khác. 🤔 💭",
      "Tức Giận Vô Cớ: Cần kiểm soát cảm xúc tiêu cực. 😠 ❌",
      "Hơi Lo Lắng Về Tương Lai: Cần tập trung vào hiện tại. 😟 🕰️",
      "Trầm Cảm và Mất Niềm Tin: Cần tìm kiếm sự giúp đỡ chuyên nghiệp. 💔 🆘",
      "Yêu Thương Bản Thân: Tự tin và chấp nhận chính mình. 💖 💪",
      "Cảm Thấy Mệt Mỏi Thể Chất: Cần nghỉ ngơi nhiều hơn. 😫 🛌",
      "Ghen Tị và Bất Mãn: So sánh bản thân với người khác. 😤 🤷‍♀️",
      "Tâm Lý Vững Vàng: Có khả năng vượt qua mọi áp lực. 🛡️ 🧱",
      "Cần Tìm Kiếm Mục Đích: Thiếu động lực và định hướng. ❓ 🧭",
      "Niềm Vui Lây Lan: Bạn trở thành nguồn cảm hứng tích cực. contagio 😊",
      "Cảm Thấy Bị Phản Bội: Lòng tin bị lung lay. 🔪 💔",
      "Hơi Hồi Hộp: Chờ đợi một sự kiện quan trọng sắp tới. 😬 ⏳",
      "Hòa Hợp Với Mọi Người: Các mối quan hệ xã hội tuyệt vời. 🫂 🤝",
      "Tâm Trạng Phụ Thuộc Vào Thời Tiết: Dễ bị ảnh hưởng bởi môi trường. 🌦️ 😟",
      "Cảm Thấy Bị Lợi Dụng: Cần thiết lập ranh giới rõ ràng. ⚠️ ⛔",
      "Tâm Trạng Ổn Định: Không có gì đáng lo ngại. 😌 ✅",
      "Sợ Hãi và Lo Lắng Quá Mức: Tinh thần bị suy sụp. 😨 💥",
      "Thỏa Mãn Với Thành Tựu: Hạnh phúc vì công việc đã hoàn thành. 🏆 😊",
      "Hơi Hờ Hững: Cần tìm lại sự hứng thú. 😒 💡",
      "Dễ Dàng Tha Thứ: Buông bỏ được sự oán hận. 🙏 🎈",
      "Cần Tập Trung Vào Việc Thiền Định: Giúp cân bằng cảm xúc. 🧘 🧠",
      "Cảm Thấy Bị Áp Lực: Do kỳ vọng quá lớn từ bản thân. 😥 📈",
      "Hạnh Phúc Tuyệt Đối: Cảm thấy được yêu thương và trân trọng. ❤️ 🥰",
      "Cần Ăn Uống Lành Mạnh Hơn: Tâm trạng bị ảnh hưởng bởi chế độ ăn. 🍎 🧠",
      "Tự Do và Tự Chủ: Tinh thần được giải phóng. 🕊️ 🗝️",
      "Tâm Trạng Cải Thiện Dần Dần: Mọi thứ đang tốt lên. 🐢 ⏫",
      "Cảm Thấy Mắc Kẹt: Không tìm thấy lối thoát cho vấn đề. 🕸️ 🚪",
      "Nên Dành Thời Gian Cho Sở Thích: Giúp tăng cường tinh thần. 🎨 😊",
      "Tuyệt Vọng và Mất Phương Hướng: Cần sự can thiệp ngay lập tức. 🆘 💔",
      "Cười Rộ và Vui Vẻ: Lan tỏa năng lượng tích cực. 😂 ☀️",
      "Cần Giảm Sử Dụng Mạng Xã Hội: Giúp giảm căng thẳng. 📱 ⬇️",
      "Bình An Sau Cơn Bão: Vượt qua khó khăn, tâm trạng tốt hơn. 🛡️ 😌",
      "Hay Đa Nghi và Đề Phòng: Mất lòng tin vào mọi người. 🧐 🔒",
      "Tâm Trạng Giống Như Người Thân: Dễ bị ảnh hưởng bởi người xung quanh. 👥 🔄",
      "Cảm Xúc Tươi Mới: Như một khởi đầu mới. 🌿 ✨",
      "Sự Hạnh Phúc Không Cần Lý Do: Tận hưởng niềm vui thuần khiết. 🥰 💯"
    ],
    "en": [
      "Extreme Happiness: Overflowing with joy and satisfaction in life. 😄✨",
      "Happy and Comfortable: Optimistic spirit, no burden. 😊 🎈",
      "Calm and Stable: No overly strong emotions, keeping neutrality. 😌 ⚖️",
      "Sad and Gloomy: Feeling depressed, need to find someone to share. 😔 🌧️",
      "Excited and Passionate: Ready for new challenges. 🔥 🚀",
      "Feeling Slightly Lonely: Need to reconnect with friends. 🧍 📞",
      "Serene Soul: Reached complete inner peace. 🧘 🕉️",
      "Grateful and Content: Feeling lucky with what you have. 🙏 😊",
      "Need to Think Carefully: Mood easily swayed by others' opinions. 🤔 💭",
      "Unreasonably Angry: Need to control negative emotions. 😠 ❌",
      "Slightly Anxious about Future: Need to focus on the present. 😟 🕰️",
      "Depressed and Lost Faith: Need to seek professional help. 💔 🆘",
      "Self-Love: Confident and accepting yourself. 💖 💪",
      "Feeling Physically Tired: Need more rest. 😫 🛌",
      "Jealous and Dissatisfied: Comparing yourself with others. 😤 🤷‍♀️",
      "Strong Psychology: Capable of overcoming all pressure. 🛡️ 🧱",
      "Need to Find Purpose: Lack of motivation and direction. ❓ 🧭",
      "Contagious Joy: You become a source of positive inspiration. contagio 😊",
      "Feeling Betrayed: Trust is shaken. 🔪 💔",
      "Slightly Nervous: Waiting for an upcoming important event. 😬 ⏳",
      "Harmony with Everyone: Excellent social relationships. 🫂 🤝",
      "Mood Depends on Weather: Easily influenced by the environment. 🌦️ 😟",
      "Feeling Exploited: Need to set clear boundaries. ⚠️ ⛔",
      "Stable Mood: Nothing to worry about. 😌 ✅",
      "Excessive Fear and Anxiety: Spirit is collapsing. 😨 💥",
      "Satisfied with Achievement: Happy because work is done. 🏆 😊",
      "Slightly Indifferent: Need to find interest again. 😒 💡",
      "Easily Forgiving: Letting go of resentment. 🙏 🎈",
      "Need to Focus on Meditation: Helps balance emotions. 🧘 🧠",
      "Feeling Pressured: Due to excessive expectations from self. 😥 📈",
      "Absolute Happiness: Feeling loved and cherished. ❤️ 🥰",
      "Need to Eat Healthier: Mood affected by diet. 🍎 🧠",
      "Free and Independent: Spirit is liberated. 🕊️ 🗝️",
      "Mood Improving Gradually: Everything is getting better. 🐢 ⏫",
      "Feeling Stuck: Cannot find a way out of the problem. 🕸️ 🚪",
      "Should Spend Time on Hobbies: Helps boost spirit. 🎨 😊",
      "Desperate and Disoriented: Need immediate intervention. 🆘 💔",
      "Laughing and Cheerful: Spreading positive energy. 😂 ☀️",
      "Need to Reduce Social Media Use: Helps reduce stress. 📱 ⬇️",
      "Peace After Storm: Overcoming difficulty, mood is better. 🛡️ 😌",
      "Suspicious and Guarded: Losing trust in everyone. 🧐 🔒",
      "Mood Like Relatives: Easily influenced by surrounding people. 👥 🔄",
      "Fresh Emotions: Like a new beginning. 🌿 ✨",
      "Happiness Without Reason: Enjoying pure joy. 🥰 💯"
    ]
  }
];