export default {
  common: { cancel: "Cancelar", save: "Guardar", delete: "Eliminar", close: "Cerrar", confirm: "Confirmar", copied: "¡Copiado!", copyData: "Copiar datos", copiedClipboard: "Copiado al portapapeles" },
  home: { title: "xKey", totalAssets: "Activos totales", offlineVault: "Bóveda sin conexión", importCSV: "Importar CSV seguro", importDesc: "Sus datos serán cifrados y almacenados localmente sin conexión.", addWallet: "Añadir billetera", noWallets: "No se encontraron billeteras.", unlocking: "Desbloqueando bóveda...", importSuccess: "Se importaron {count} billeteras de {folder}", duplicatesSkipped: " ({count} duplicados omitidos)", walletDeleted: "Billetera eliminada", folderDeleted: 'Carpeta "{name}" eliminada', backupImported: "Respaldo importado: {count} billeteras", deleteWalletConfirm: '¿Eliminar billetera "{name}"?', deleteFolderConfirm: '¿Eliminar todas las billeteras en "{name}"?' },
  restore: { title: "Restaurar respaldo", desc: "Ingrese la contraseña usada al crear este respaldo.", placeholder: "Contraseña del respaldo", button: "Restaurar", wrongPassword: "Contraseña incorrecta o archivo corrupto" },
  settings: { title: "Configuración", appearance: "Apariencia", darkMode: "Modo oscuro", lightMode: "Modo claro", language: "Idioma", languageDesc: "Seleccione su idioma preferido", backupTitle: "Respaldo de la bóveda", backupSubtitle: "Cifrado y portátil — funciona en cualquier dispositivo", backupInfo: "Sus billeteras están cifradas con una contraseña que usted elige. Este respaldo puede restaurarse en cualquier dispositivo.", createBackup: "Crear respaldo cifrado", backupPassword: "Contraseña", confirmPassword: "Confirmar contraseña", passwordMin: "Mín. 6 caracteres", reenterPassword: "Reingrese la contraseña", passwordWarning: "Si olvida esta contraseña, el respaldo no podrá recuperarse.", exportBackup: "Exportar respaldo", exporting: "Exportando...", passwordMinError: "La contraseña debe tener al menos 6 caracteres", passwordMismatch: "Las contraseñas no coinciden", exportSuccess: "Respaldo exportado exitosamente", exportFailed: "Error en la exportación.", exportError: "Error al exportar.", dangerZone: "Zona de peligro", dangerSubtitle: "Acciones destructivas irreversibles", wipeAll: "Borrar todos los datos", wipeDesc: "Elimina la Clave AES y todas las billeteras. No se pueden recuperar.", wipeConfirm: "ADVERTENCIA: Se eliminarán todas las billeteras. ¿Está seguro?" },
  createWallet: { title: "Añadir billetera", tabManual: "Entrada manual", tabGenerate: "Generar aleatoria", generateInfo: "Genere una billetera nueva con clave privada aleatoria segura y frase mnemónica.", generateExplain: "Las billeteras se crean usando matemáticas puras — sin Internet. La frase semilla sigue el estándar BIP-39 y funciona en cualquier billetera compatible.", walletName: "Nombre", walletNamePlaceholder: "Ej: Mi billetera principal", address: "Dirección", addressRequired: "(requerido)", privateKey: "Clave privada", seedPhrase: "Frase semilla", balance: "Saldo", notes: "Notas", notesPlaceholder: "Notas sobre esta billetera...", optional: "(opcional)", duplicateWarning: "Esta dirección ya existe en su bóveda", fillRequired: "Complete al menos una dirección, clave privada o frase semilla", generateButton: "Generar", generateAnother: "Generar otra", mnemonic12: "Mnemónica (12 palabras)", copyMnemonic: "Copiar mnemónica", backupWarning: "Respalde su Clave Privada y Mnemónica AHORA.", saveToVault: "Guardar en la bóveda", walletCreated: "Billetera creada y guardada", walletAdded: "Billetera añadida", walletAddedDuplicate: "Billetera añadida (dirección duplicada)", addressExplain: "Dirección pública de la billetera. Es seguro compartirla.", pkExplain: "La clave secreta que controla esta billetera. NUNCA la comparta.", seedExplain: "12 o 24 palabras que pueden regenerar la clave privada. Almacene sin conexión." },
  walletCard: { unnamed: "Billetera sin nombre", noAddress: "Sin dirección", balanceLabel: "Saldo", rename: "Renombrar", delete: "Eliminar", edit: "Editar", editWallet: "Editar billetera", saveChanges: "Guardar cambios", saved: "Cambios guardados", added: "Añadida", address: "Dirección", privateKey: "Clave privada", seedPhrase: "Frase semilla", notes: "Notas", notesPlaceholder: "Notas...", autoHide: "(ocultar auto en 30s)", pkWarning: "Quien tenga esta clave tiene control total." },
  actionBar: { searchPlaceholder: "Buscar por dirección o nombre...", allWallets: "Todas", hasPk: "Tiene clave privada", hasSeed: "Tiene frase semilla", hasBalance: "Saldo > 0", empty: "Saldo = 0", defaultOrder: "Orden predeterminado", nameAsc: "Nombre A → Z", nameDesc: "Nombre Z → A", newestFirst: "Más reciente", oldestFirst: "Más antiguo", balanceHigh: "Saldo alto → bajo", balanceLow: "Saldo bajo → alto", addressAsc: "Dirección A → Z" },
  duplicates: { title: "Detector de duplicados", noDuplicates: "Sin duplicados", allUnique: "Todas las direcciones son únicas.", foundGroups: "{count} dirección(es) con duplicados.", hasPK: "Tiene PK" },
  dashboard: { title: "Analítica", totalWallets: "Total", activeBalance: "Activas (Saldo > 0)", emptyWallets: "Billeteras vacías", withPK: "Con clave privada", distribution: "Distribución por carpeta", folders: "carpetas", totalValue: "Valor total" },
  exportCSV: { title: "Exportar CSV", selectColumns: "Columnas ({count} billeteras)", sensitiveWarning: "Datos sensibles se exportarán en texto plano. Maneje con precaución.", copy: "Copiar", download: "Descargar", copySuccess: "{count} billeteras copiadas", exportSuccess: "CSV exportado", colName: "Nombre", colAddress: "Dirección", colBalance: "Saldo", colFolder: "Carpeta", colPrivateKey: "Clave privada", colSeedPhrase: "Frase semilla" },
  authError: { vaultLocked: "Bóveda bloqueada", retry: "Reintentar", wipeReset: "Borrar y reiniciar", wipeExplain: "Clave de cifrado perdida o corrupta. Todos los datos se eliminarán permanentemente.", confirmWipe: "Confirmar borrado", wiping: "Borrando..." },
};
