export default {
  common: { cancel: "Batal", save: "Simpan", delete: "Hapus", close: "Tutup", confirm: "Konfirmasi", copied: "Disalin!", copyData: "Salin Data", copiedClipboard: "Disalin ke clipboard" },
  home: { title: "xKey", totalAssets: "Total Aset", offlineVault: "Brankas Offline", importCSV: "Impor CSV Aman", importDesc: "Data Anda akan dienkripsi dan disimpan secara lokal offline.", addWallet: "Tambah Dompet", noWallets: "Tidak ada dompet yang cocok.", unlocking: "Membuka brankas...", importSuccess: "Berhasil mengimpor {count} dompet dari {folder}", duplicatesSkipped: " ({count} duplikat dilewati)", walletDeleted: "Dompet dihapus", folderDeleted: 'Folder "{name}" dihapus', backupImported: "Cadangan diimpor: {count} dompet", deleteWalletConfirm: 'Hapus dompet "{name}"?', deleteFolderConfirm: 'Hapus semua dompet di folder "{name}"?' },
  restore: { title: "Pulihkan Cadangan", desc: "Masukkan kata sandi yang digunakan saat membuat cadangan ini.", placeholder: "Kata sandi cadangan", button: "Pulihkan", wrongPassword: "Kata sandi salah atau file rusak" },
  settings: { title: "Pengaturan", appearance: "Tampilan", darkMode: "Mode Gelap", lightMode: "Mode Terang", language: "Bahasa", languageDesc: "Pilih bahasa yang Anda inginkan", backupTitle: "Cadangan Brankas", backupSubtitle: "Terenkripsi & portabel — berfungsi di semua perangkat", backupInfo: "Dompet Anda dienkripsi dengan kata sandi pilihan Anda. Cadangan ini dapat dipulihkan di perangkat mana pun.", createBackup: "Buat Cadangan Terenkripsi", backupPassword: "Kata Sandi Cadangan", confirmPassword: "Konfirmasi Kata Sandi", passwordMin: "Min. 6 karakter", reenterPassword: "Masukkan ulang kata sandi", passwordWarning: "Jika Anda lupa kata sandi ini, cadangan tidak dapat dipulihkan.", exportBackup: "Ekspor Cadangan", exporting: "Mengekspor...", passwordMinError: "Kata sandi minimal 6 karakter", passwordMismatch: "Kata sandi tidak cocok", exportSuccess: "Cadangan portabel berhasil diekspor", exportFailed: "Ekspor gagal.", exportError: "Error saat mengekspor cadangan.", dangerZone: "Zona Bahaya", dangerSubtitle: "Tindakan destruktif yang tidak dapat dibatalkan", wipeAll: "Hapus Semua Data Brankas", wipeDesc: "Tindakan ini menghapus Kunci Enkripsi AES dan semua dompet terenkripsi. Tidak dapat dipulihkan.", wipeConfirm: "PERINGATAN: Semua dompet terenkripsi akan dihapus. Yakin?" },
  createWallet: { title: "Tambah Dompet", tabManual: "Input Manual", tabGenerate: "Buat Acak", generateInfo: "Buat dompet baru dengan kunci privat acak yang aman dan frasa mnemonik.", generateExplain: "Dompet dibuat menggunakan matematika murni — tidak perlu internet. Frasa benih mengikuti standar BIP-39 dan berfungsi di dompet mana pun yang kompatibel.", walletName: "Nama Dompet", walletNamePlaceholder: "Contoh: Dompet Utama Saya", address: "Alamat", addressRequired: "(wajib)", privateKey: "Kunci Privat", seedPhrase: "Frasa Benih", balance: "Saldo", notes: "Catatan", notesPlaceholder: "Catatan tentang dompet ini...", optional: "(opsional)", duplicateWarning: "Alamat ini sudah ada di brankas Anda", fillRequired: "Harap isi setidaknya alamat, kunci privat, atau frasa benih", generateButton: "Buat Dompet", generateAnother: "Buat lagi", mnemonic12: "Mnemonik (12 kata)", copyMnemonic: "Salin mnemonik", backupWarning: "Cadangkan sekarang. Setelah disimpan akan dienkripsi.", saveToVault: "Simpan ke Brankas", walletCreated: "Dompet dibuat dan disimpan", walletAdded: "Dompet ditambahkan ke brankas", walletAddedDuplicate: "Dompet ditambahkan (alamat duplikat)", addressExplain: "Alamat publik dompet. Aman untuk dibagikan — seperti nomor rekening bank.", pkExplain: "Kunci rahasia yang mengontrol dompet ini. JANGAN pernah membagikannya.", seedExplain: "12 atau 24 kata yang dapat meregenerasi kunci privat. Simpan offline." },
  walletCard: { unnamed: "Dompet Tanpa Nama", noAddress: "Tidak Ada Alamat", balanceLabel: "Saldo", rename: "Ganti Nama", delete: "Hapus", edit: "Edit", editWallet: "Edit Dompet", saveChanges: "Simpan Perubahan", saved: "Perubahan disimpan", added: "Ditambahkan", address: "Alamat", privateKey: "Kunci Privat", seedPhrase: "Frasa Benih", notes: "Catatan", notesPlaceholder: "Catatan...", autoHide: "(otomatis sembunyi dalam 30 detik)", pkWarning: "Siapa pun yang memiliki kunci ini memiliki kontrol penuh." },
  actionBar: { searchPlaceholder: "Cari berdasarkan alamat atau nama...", allWallets: "Semua Dompet", hasPk: "Memiliki Kunci Privat", hasSeed: "Memiliki Frasa Benih", hasBalance: "Saldo > 0", empty: "Saldo = 0", defaultOrder: "Urutan Default", nameAsc: "Nama A → Z", nameDesc: "Nama Z → A", newestFirst: "Terbaru Dulu", oldestFirst: "Terlama Dulu", balanceHigh: "Saldo Tinggi → Rendah", balanceLow: "Saldo Rendah → Tinggi", addressAsc: "Alamat A → Z" },
  duplicates: { title: "Detektor Duplikat", noDuplicates: "Tidak ada duplikat", allUnique: "Semua alamat dompet unik.", foundGroups: "Ditemukan {count} alamat dengan entri duplikat.", hasPK: "Ada PK" },
  dashboard: { title: "Analitik", totalWallets: "Total Dompet", activeBalance: "Aktif (Saldo > 0)", emptyWallets: "Dompet Kosong", withPK: "Dengan Kunci Privat", distribution: "Distribusi Aset per Folder", folders: "folder", totalValue: "Total Nilai Brankas" },
  exportCSV: { title: "Ekspor CSV", selectColumns: "Pilih kolom ({count} dompet)", sensitiveWarning: "Data sensitif akan diekspor dalam teks biasa. Tangani dengan sangat hati-hati.", copy: "Salin", download: "Unduh", copySuccess: "{count} dompet disalin ke clipboard", exportSuccess: "CSV berhasil diekspor", colName: "Nama", colAddress: "Alamat", colBalance: "Saldo", colFolder: "Folder", colPrivateKey: "Kunci Privat", colSeedPhrase: "Frasa Benih" },
  authError: { vaultLocked: "Brankas Terkunci", retry: "Coba Lagi", wipeReset: "Hapus Brankas & Reset", wipeExplain: "Kunci enkripsi hilang atau rusak. Semua data brankas akan dihapus permanen.", confirmWipe: "Konfirmasi Hapus", wiping: "Menghapus..." },
};
